import type { Guide } from "@/lib/types";

const healthMinistry = { name: "Federal Ministry of Health", url: "https://www.bundesgesundheitsministerium.de/en/topics/health-guide-for-asylum-seekers/general-information.html", note: "Official health-system information" };
const euHealth = { name: "European Commission — healthcare in Germany", url: "https://employment-social-affairs.ec.europa.eu/policies-and-activities/moving-working-europe/eu-social-security-coordination/country-information/germany_en", note: "Cross-border social-security information" };
const bafin = { name: "BaFin consumer information", url: "https://www.bafin.de/EN/Verbraucher/verbraucher_node_en.html", note: "Germany's financial supervisory authority" };
const bundesbank = { name: "Deutsche Bundesbank", url: "https://www.bundesbank.de/en/tasks/topics/basic-bank-account-666926", note: "Official basic payment account information" };
const db = { name: "Deutsche Bahn — Deutschland-Ticket", url: "https://int.bahn.de/en/offers/regional/deutschland-ticket", note: "Current offer terms and travel scope" };
const federalTransport = { name: "Federal Government — Deutschlandticket", url: "https://www.bundesregierung.de/breg-en/news/deutschlandticket-2134074", note: "Government overview" };
const stats = { name: "Federal Statistical Office", url: "https://www.destatis.de/EN/Home/_node.html", note: "Official German statistics" };
const consumer = { name: "Consumer advice centres", url: "https://www.verbraucherzentrale.de/", note: "Independent consumer information in German" };

export const lifeServicesGuides: Guide[] = [
  {
    slug: "german-health-insurance", title: "Health insurance in Germany: start with your status", description: "Understand Germany's public and private health-insurance pathways, the questions to ask, and how to avoid coverage gaps.", category: "healthcare", eyebrow: "Healthcare", updated: "2026-09-23", readingMinutes: 11, featured: true,
    summary: "Health insurance is generally essential in Germany, but the right setup depends on employment, income, study, family, previous coverage, and residence status. Confirm eligibility before treating a comparison as a decision.",
    takeaways: ["Public and private insurance are systems, not simple product tiers.", "Eligibility and future consequences matter more than an introductory price.", "Employers, universities, and immigration processes may need proof.", "For treatment decisions, speak to a medical professional—not an insurance guide."],
    sections: [
      { heading: "Map your status first", paragraphs: ["Write down whether you are employed, self-employed, studying, job-seeking, joining family, retired, or temporarily posted. Add age, previous insurance, expected income, dependants, and residence status where relevant.", "These facts shape whether statutory insurance, private insurance, cross-border coverage, family insurance, or another arrangement may apply. An insurer or independent qualified adviser should confirm the result." ] },
      { heading: "Public and private are structurally different", paragraphs: ["Statutory health insurance operates within a regulated social-insurance framework; contributions and family arrangements follow rules that are not equivalent to an individually underwritten private contract. Private insurance uses contractual benefits, premiums, and underwriting considerations.", "Compare access, benefits, dependants, long-term affordability, switching implications, billing, and support—not only the first monthly amount."], callout: { title: "A long-term decision", text: "Switching systems later may be restricted by your circumstances. Get individual advice before making a choice with lasting effects.", tone: "warning" } },
      { heading: "Before your start date", paragraphs: ["Ask the insurer when coverage begins, what evidence you receive, how dependants are handled, and what happens before the insurance card arrives. Give employers, universities, or authorities the correct confirmation channel.", "If you have an EHIC or other cross-border document, check what it covers in your specific situation. Travel or temporary cover is not automatically a substitute for residence-based insurance." ] },
      { heading: "Using healthcare", paragraphs: ["Keep the insurer's contact details and learn how to find contracted doctors, access out-of-hours care, and handle emergencies. Ask the provider before non-routine treatment whether a referral, approval, or personal payment could apply.", "This guide explains the system only. Symptoms, diagnosis, medicines, and treatment decisions require a qualified healthcare professional." ] },
    ],
    faqs: [
      { question: "Is public or private insurance better?", answer: "Neither is universally better. Eligibility, dependants, income, expected length of stay, benefits, and long-term costs all matter." },
      { question: "Can I use my EHIC after moving?", answer: "EHIC is designed for necessary healthcare during temporary stays under EU coordination rules. A move, work, or study situation can require a different arrangement. Confirm with the responsible institution." },
      { question: "When should I arrange insurance?", answer: "Research it before arrival or before your employment or study starts. Effective dates and proof requirements can affect other processes." },
    ], sources: [healthMinistry, euHealth], related: ["moving-to-germany", "first-30-days-germany", "working-in-germany", "cost-of-living-germany"],
  },
  {
    slug: "german-bank-account", title: "Opening a bank account in Germany", description: "Compare German payment accounts by access, fees, identification, cash needs, support, and deposit protection—not marketing alone.", category: "money", eyebrow: "Money", updated: "2026-09-23", readingMinutes: 9, featured: true,
    summary: "A useful German account should fit how you receive income, pay rent and bills, use cash, travel, and get support. An app-first account and a branch account solve different problems.",
    takeaways: ["Compare the full fee schedule.", "Check identification and residence requirements before applying.", "Understand cards, cash access, overdrafts, and support.", "Never send login codes or authorise a transfer for someone claiming to help."],
    sections: [
      { heading: "Define the job of the account", paragraphs: ["List the payments you need to receive and make: salary, rent, direct debits, transfers, card purchases, cash withdrawals, and international payments. Note whether you need a German IBAN, branch help, a joint account, or cash deposits.", "A provider with a smooth app may be ideal for one person and unsuitable for someone who needs in-person service or frequent cash handling." ] },
      { heading: "Compare beyond the headline price", paragraphs: ["Read monthly conditions, card fees, ATM rules, foreign-currency charges, cash-deposit options, overdraft terms, support languages, and cancellation procedures. Check which legal entity holds the account and which deposit-guarantee system is relevant.", "Promotional rewards should not outweigh the recurring cost or operational fit."], bullets: ["Monthly account cost and waiver conditions", "Debit and credit card type", "ATM and cash-deposit access", "Transfer and currency fees", "Customer support channels", "Deposit protection information"] },
      { heading: "Prepare for identification", paragraphs: ["Banks must verify customers. Accepted identity documents, address evidence, tax-residence questions, and video or in-person procedures vary. Use the bank's current application instructions.", "If an ordinary account application is declined, learn about Germany's statutory basic payment account framework and the conditions described by the Bundesbank and BaFin." ] },
      { heading: "Keep it secure", paragraphs: ["Use a unique password, protect the device and authentication method, and read payment confirmations before approving them. A bank will not need your one-time code to ‘reverse’ a fraud event.", "If you suspect compromise, use the bank's official emergency channel immediately and document what happened."], callout: { title: "Approval means payment", text: "Never approve an authentication request you did not initiate, even when a caller claims to be from the bank.", tone: "warning" } },
    ],
    faqs: [
      { question: "Do I need a German IBAN?", answer: "SEPA rules support eligible euro accounts across participating countries, but a German account can still simplify some local processes. Choose based on practical needs and provider terms." },
      { question: "Can I open an account before registering?", answer: "Requirements vary by provider and applicant. Check the current document list before applying." },
      { question: "What is a basic payment account?", answer: "German law provides a framework for a Basiskonto for eligible consumers. Consult BaFin or the Bundesbank for scope and complaint routes." },
    ], sources: [bafin, bundesbank], related: ["german-tax-id", "cost-of-living-germany", "first-30-days-germany", "schufa-germany"],
  },
  {
    slug: "deutschlandticket", title: "Deutschlandticket: what it covers and what to check", description: "Understand the nationwide local-transport subscription, its limits, cancellation terms, and the journeys it does not normally cover.", category: "transport", eyebrow: "Transport", updated: "2026-09-23", readingMinutes: 7, featured: true,
    summary: "The Deutschlandticket is a subscription for eligible local and regional public transport across Germany. It is not generally a ticket for long-distance ICE, IC, or EC services, and provider terms matter.",
    takeaways: ["Check the current price and conditions before subscribing.", "Local and regional transport is the core scope.", "Long-distance trains are generally outside the offer.", "Cancellation deadlines and app access depend on the seller."],
    sections: [
      { heading: "Understand the network, not just the name", paragraphs: ["The ticket is designed for participating local and regional services across Germany, including many buses, trams, U-Bahn, S-Bahn, and regional trains. The exact service category matters more than the geographical distance.", "ICE, IC, and EC are generally long-distance products and are normally excluded. Do not board based only on the destination or platform; check the train category in the journey planner." ] },
      { heading: "It is a subscription", paragraphs: ["Buy from a recognised transport provider and read its billing, start-date, cancellation, app, and customer-service terms. The nationally defined product can still be sold through different provider interfaces.", "Check the current price from an official source. Prices and policy details can change, so a static article should not be your final checkout reference."], callout: { title: "Check the cancellation deadline", text: "If you need the ticket for one month, confirm when and how the chosen provider requires cancellation before you subscribe.", tone: "warning" } },
      { heading: "Plan a journey correctly", paragraphs: ["Use an operator planner and select local transport only when testing whether a trip fits the ticket. Leave enough transfer time and look for replacement buses or construction notices.", "Special tourist services, first class, bicycles, dogs, and additional passengers may need separate tickets. Check the local operator rules." ] },
    ],
    faqs: [
      { question: "Can I take an ICE with the Deutschlandticket?", answer: "Generally no. The offer is centred on local and regional transport. Check the specific service and any officially published exception." },
      { question: "Is the ticket valid in every city?", answer: "It is widely valid on participating local and regional services throughout Germany, but check special services and local carriage rules." },
      { question: "Does it cancel automatically?", answer: "Do not assume so. It is a subscription; review the seller's cancellation terms and deadline." },
    ], sources: [db, federalTransport], related: ["first-30-days-germany", "living-mannheim", "best-cities-germany", "cost-of-living-germany"],
  },
  {
    slug: "cost-of-living-germany", title: "Cost of living in Germany: build your own realistic budget", description: "Use a practical budget framework for housing, insurance, transport, food, utilities, and one-off moving costs without relying on misleading averages.", category: "money", eyebrow: "Money", updated: "2026-09-23", readingMinutes: 10, featured: true,
    summary: "Germany does not have one meaningful cost of living. Housing, household type, employment or student status, transport, and insurance create much larger differences than a national average suggests.",
    takeaways: ["Start with the actual housing market in your target area.", "Separate recurring costs from arrival cash needs.", "Model a conservative and a stress case.", "Use official statistics for context, not as a substitute for live quotes."],
    sections: [
      { heading: "Housing sets the shape of the budget", paragraphs: ["Research current listings for homes you could realistically secure—not the median of an entire city. Record cold rent, operating costs, heating setup, electricity, internet, furnishing, deposit, and commute.", "A cheaper home can cost more overall when it creates a long commute or needs separate furnishings. Compare total monthly and initial cash requirements." ] },
      { heading: "Build the recurring baseline", paragraphs: ["Include housing, health-insurance impact, transport, groceries, mobile and internet, broadcasting contribution where applicable, household insurance choices, debt payments, and regular transfers.", "Some payroll deductions happen before net salary reaches you. Do not add them again, but make sure your net estimate is appropriate to your personal circumstances."], bullets: ["Warm rent plus excluded utilities", "Health and other insurance", "Transport", "Food and household goods", "Phone and internet", "Subscriptions and contributions", "Savings and irregular expenses"] },
      { heading: "Add the arrival layer", paragraphs: ["Temporary accommodation, deposits, travel, documents, basic furniture, kitchen items, transport passes, and overlapping rent can create a large first-month requirement even when the recurring budget works.", "Keep an emergency buffer separate from the planned move fund. A job start and first salary payment do not always line up with the date your costs begin." ] },
      { heading: "Use scenarios, not false precision", paragraphs: ["Create a base case from verified quotes, a conservative case with higher housing and travel costs, and a stress case that includes an extended housing search or delayed income. Update the model once you have real bills.", "Online calculators can help structure questions, but tax, insurance, and benefit results require reliable inputs and may need professional advice."], callout: { title: "A budget is a decision tool", text: "Avoid one-number promises. Record the date and source beside every estimate so you know what to refresh.", tone: "note" } },
    ],
    faqs: [
      { question: "How much money do I need per month?", answer: "There is no responsible universal figure. Build a budget from target-area rent, household size, insurance, transport, and your actual commitments." },
      { question: "Which city is cheapest?", answer: "City-level averages hide neighbourhood, quality, and availability. Compare homes you could actually rent and the journey required." },
      { question: "How much should I save before moving?", answer: "Cover travel, temporary housing, deposits, setup costs, ordinary spending, and a delay buffer. The amount depends on your household and certainty of income." },
    ], sources: [stats, consumer], related: ["moving-to-germany", "finding-housing-germany", "german-bank-account", "best-cities-germany"],
  },
  {
    slug: "german-sim-cards", title: "German SIM cards: choose a plan without contract surprises", description: "Compare prepaid and contract mobile plans by network, coverage, data, roaming, identification, and cancellation terms.", category: "daily-life", eyebrow: "Daily life", updated: "2026-09-23", readingMinutes: 7,
    summary: "Choose a German mobile plan by the places you need it to work, the contract commitment, and the complete recurring cost. A large data allowance is not useful on an unsuitable network or inflexible agreement.",
    takeaways: ["Check coverage at home, work, and common journeys.", "Prepaid can reduce commitment during the first weeks.", "Activation requires identity verification.", "Read renewal, price-change, and cancellation terms."],
    sections: [
      { heading: "Prepaid or contract", paragraphs: ["Prepaid plans can be practical while your address, bank setup, and long-term usage are uncertain. Contracts may offer different pricing or devices, but create a longer commitment and can involve credit checks.", "Compare the total service cost separately from any handset financing. An apparently free device is part of the economics of the agreement." ] },
      { heading: "Test the network against your life", paragraphs: ["Use provider coverage maps as a starting point, then ask people in the actual building or area. Indoor coverage and rural routes can differ from a general city-level impression.", "Check 4G and 5G availability, speed restrictions, hotspot rules, EU roaming, international calling, and whether eSIM is supported on your device." ] },
      { heading: "Activate and protect the number", paragraphs: ["German SIM activation involves identity verification. Follow the provider's official process and do not send identity documents to a reseller through an unverified chat.", "Protect account login and porting credentials. When changing provider, check notice and number-transfer steps before cancelling the old service."], callout: { title: "Use official activation channels", text: "Identity documents are valuable. Verify the provider and web address before starting video or document verification.", tone: "warning" } },
    ],
    faqs: [
      { question: "Can I buy a German SIM before registering?", answer: "Provider requirements vary. Prepaid products still require identity verification, but the accepted documents and address process differ." },
      { question: "Is eSIM always available?", answer: "No. It depends on provider, plan, and device. Confirm support before ordering." },
      { question: "Will EU roaming cover long-term use abroad?", answer: "EU roaming is subject to fair-use conditions. Check the provider's current terms if you spend extended periods outside Germany." },
    ], sources: [consumer], related: ["first-30-days-germany", "moving-to-germany", "german-bank-account", "german-supermarkets"],
  },
  {
    slug: "german-supermarkets", title: "German supermarkets: shopping, Pfand, payment, and labels", description: "A practical first-shop guide to supermarket formats, deposit returns, checkout habits, food labels, and Sunday planning.", category: "daily-life", eyebrow: "Daily life", updated: "2026-09-23", readingMinutes: 7,
    summary: "German grocery shopping is straightforward once you know the store formats, bring-your-own-bag habit, Pfand return system, checkout pace, and limited Sunday opening.",
    takeaways: ["Discount and full-range supermarkets serve different shopping needs.", "Many drink containers carry a refundable deposit.", "Bring bags and pack away from the checkout when possible.", "Plan around Sunday and public-holiday closures."],
    sections: [
      { heading: "Know the main store formats", paragraphs: ["Discounters focus on a tighter range and private labels, while full-range supermarkets generally offer more brands and specialist products. Organic chains, international grocers, weekly markets, and drugstores fill other gaps.", "Compare a normal basket rather than assuming one chain is always cheaper. Local availability, pack sizes, and promotions change the result." ] },
      { heading: "Use the Pfand system", paragraphs: ["Many beverage containers include a deposit shown separately from the shelf price. Return eligible containers through the store machine or return point and take the receipt to the checkout.", "Return systems distinguish container types and participating formats. Look for the deposit markings and follow the machine instructions rather than placing deposit containers in household recycling." ] },
      { heading: "At the checkout", paragraphs: ["Place a divider after your shopping, keep payment ready, and move purchases into the packing area or trolley promptly. Bring reusable bags or expect to pay for bags.", "Card acceptance is common but not universal across every small shop or market. Keeping a modest alternative payment method can be practical." ] },
      { heading: "Plan the week", paragraphs: ["Most ordinary supermarkets close on Sundays and public holidays, with limited exceptions such as some station or airport outlets. Check local hours rather than assuming a national schedule.", "Learn common label terms for allergens, ingredients, best-before dates, use-by dates, and unit pricing. Ask staff when a food-safety label is unclear."], callout: { title: "Best-before is not use-by", text: "German labels distinguish quality guidance from safety-related use-by dates. Follow the product's exact wording and storage instructions.", tone: "note" } },
    ],
    faqs: [
      { question: "Are Aldi and Lidl always cheapest?", answer: "They often compete strongly on price, but the lowest total depends on your basket, local stores, and promotions." },
      { question: "Can I return every bottle anywhere?", answer: "Not always. Return obligations and machine acceptance depend on container and retailer. Use the deposit markings and store guidance." },
      { question: "Where can I shop on Sunday?", answer: "Options are limited and local. Some stations, airports, bakeries, or designated openings may be available; check current local information." },
    ], sources: [consumer], related: ["cost-of-living-germany", "german-bank-account", "first-30-days-germany", "german-sim-cards"],
  },
];
