import type { Guide } from "@/lib/types";

const healthMinistry = { name: "Federal Ministry of Health", url: "https://www.bundesgesundheitsministerium.de/en/topics/health-guide-for-asylum-seekers/general-information.html", note: "Official health-system information" };
const euHealth = { name: "European Commission — healthcare in Germany", url: "https://employment-social-affairs.ec.europa.eu/policies-and-activities/moving-working-europe/eu-social-security-coordination/country-information/germany_en", note: "Cross-border social-security information" };
const bafin = { name: "BaFin consumer information", url: "https://www.bafin.de/EN/Verbraucher/verbraucher_node_en.html", note: "Germany's financial supervisory authority" };
const bundesbank = { name: "Deutsche Bundesbank", url: "https://www.bundesbank.de/en/tasks/topics/basic-bank-account-666926", note: "Official basic payment account information" };
const db = { name: "Deutsche Bahn — Deutschland-Ticket", url: "https://int.bahn.de/en/offers/regional/deutschland-ticket", note: "Current offer terms and travel scope" };
const federalTransport = { name: "Federal Government — Deutschlandticket", url: "https://www.bundesregierung.de/breg-en/news/deutschlandticket-2134074", note: "Government overview" };
const stats = { name: "Federal Statistical Office", url: "https://www.destatis.de/EN/Home/_node.html", note: "Official German statistics" };
const consumer = { name: "Consumer advice centres", url: "https://www.verbraucherzentrale.de/", note: "Independent consumer information in German" };
const n26 = { name: "N26 account plans", url: "https://n26.com/en-de/plans", note: "Primary provider pricing and eligibility" };
const revolut = { name: "Revolut Germany fees", url: "https://www.revolut.com/de-DE/legal/standard-fees/", note: "Primary provider fee schedule" };
const wise = { name: "Wise Germany pricing", url: "https://wise.com/de/pricing/", note: "Primary provider pricing" };
const mobileRegulator = { name: "Federal Network Agency — prepaid identification", url: "https://www.bundesnetzagentur.de/DE/Fachthemen/Telekommunikation/OeffentlicheSicherheit/IdentverfahrenPrepaid/start.html", note: "Official identification rules" };
const dbNavigator = { name: "DB Navigator", url: "https://www.bahn.de/service/mobile/db-navigator", note: "Official journey planner and ticket app" };
const nextbike = { name: "nextbike", url: "https://www.nextbike.de/de/", note: "Primary app and national reference prices" };

export const lifeServicesGuides: Guide[] = [
  {
    slug: "german-health-insurance", title: "Health insurance in Germany: start with your status", description: "Understand Germany's public and private health-insurance pathways, the questions to ask, and how to avoid coverage gaps.", category: "healthcare", eyebrow: "Healthcare", updated: "2026-09-23", readingMinutes: 11, featured: true,
    summary: "Health insurance is generally essential in Germany, but the right setup depends on employment, income, study, family, previous coverage, and residence status. Confirm eligibility before treating a comparison as a decision.",
    takeaways: ["Public and private insurance are systems, not simple product tiers.", "Eligibility and future consequences matter more than an introductory price.", "Employers, universities, and immigration processes may need proof.", "For treatment decisions, speak to a medical professional—not an insurance guide."],
    sections: [
      { heading: "Map your status first", paragraphs: ["Write down whether you are employed, self-employed, studying, job-seeking, joining family, retired, or temporarily posted. Add age, previous insurance, expected income, dependants, and residence status where relevant.", "These facts shape whether statutory insurance, private insurance, cross-border coverage, family insurance, or another arrangement may apply. An insurer or independent qualified adviser should confirm the result." ] },
      { heading: "Public and private are structurally different", paragraphs: ["Statutory health insurance operates within a regulated social-insurance framework; contributions and family arrangements follow rules that are not equivalent to an individually underwritten private contract. Private insurance uses contractual benefits, premiums, and underwriting considerations.", "Compare access, benefits, dependants, long-term affordability, switching implications, billing, and support—not only the first monthly amount."], callout: { title: "A long-term decision", text: "Switching systems later may be restricted by your circumstances. Get individual advice before making a choice with lasting effects.", tone: "warning" } },
      { heading: "Before your start date", paragraphs: ["Ask the insurer when coverage begins, what evidence you receive, how dependants are handled, and what happens before the insurance card arrives. Give employers, universities, or authorities the correct confirmation channel.", "If you have an EHIC or other cross-border document, check what it covers in your specific situation. Travel or temporary cover is not automatically a substitute for residence-based insurance." ] },
      { heading: "Using healthcare", paragraphs: ["Keep the insurer's contact details and learn how to find contracted doctors, access out-of-hours care, and handle emergencies. Ask the provider before non-routine treatment whether a referral, approval, or personal payment could apply.", "This guide explains the system only. Symptoms, diagnosis, medicines, and treatment decisions require a qualified healthcare professional." ] },
    ],
    faqs: [
      { question: "Is public or private insurance better?", answer: "Neither is universally better. Eligibility, dependants, income, expected length of stay, benefits, and long-term costs all matter." },
      { question: "Can I use my EHIC after moving?", answer: "EHIC is designed for necessary healthcare during temporary stays under EU coordination rules. A move, work, or study situation can require a different arrangement. Confirm with the responsible institution." },
      { question: "When should I arrange insurance?", answer: "Research it before arrival or before your employment or study starts. Effective dates and proof requirements can affect other processes." },
    ], sources: [healthMinistry, euHealth], related: ["moving-to-germany", "first-30-days-germany", "working-in-germany", "cost-of-living-germany"],
  },
  {
    slug: "german-bank-account", title: "Opening a bank account in Germany", description: "Compare German payment accounts by access, fees, identification, cash needs, support, and deposit protection—not marketing alone.", category: "money", eyebrow: "Money", updated: "2026-09-23", readingMinutes: 9, featured: true,
    summary: "A useful German account should fit how you receive income, pay rent and bills, use cash, travel, and get support. An app-first account and a branch account solve different problems.",
    takeaways: ["Compare the full fee schedule.", "Check identification and residence requirements before applying.", "Understand cards, cash access, overdrafts, and support.", "Never send login codes or authorise a transfer for someone claiming to help."],
    sections: [
      { heading: "Choose the right type of account", paragraphs: ["For salary, rent, direct debits and ordinary bills, prioritise a current account that gives you an IBAN, supports SEPA transfers and fits your cash needs. If you regularly exchange currencies, a multi-currency service can be useful as a second account rather than automatically replacing your main German current account.", "As a practical 2026 shortlist: N26 and Revolut are app-first options; Wise focuses on multi-currency transfers; Trade Republic combines investing with current-account functions. A Sparkasse, Volksbank, Commerzbank or Deutsche Bank can be more practical when you need branch service or cash deposits."], resources: [
        { label: "N26", url: "https://n26.com/en-de/plans", note: "Standard: €0/month, virtual debit card and two free euro ATM withdrawals; check eligibility." },
        { label: "Revolut", url: "https://www.revolut.com/de-DE/bank-account/", note: "Standard subscription: €0/month for eligible German residents; card delivery and usage limits can cost extra." },
        { label: "Wise", url: "https://wise.com/de/account/", note: "Free registration and multi-currency details; transfer and conversion fees vary by currency." },
        { label: "Trade Republic", url: "https://traderepublic.com/en-de", note: "Investment-led provider with current-account features; confirm that Girokonto functions are activated before using it for salary and bills." },
      ] },
      { heading: "Compare costs and practical limits", paragraphs: ["Do not compare only the monthly fee. Check the physical-card cost, free cash-withdrawal allowance, ATM minimums, foreign-currency markup, cash deposits, customer-support route and whether the provider supplies a German IBAN.", "A €0 plan is not automatically the cheapest if you withdraw cash often or need a physical card. Provider prices below were checked on 24 September 2026 and should be rechecked immediately before opening."], bullets: ["N26 Standard: €0/month; virtual card; two free euro ATM withdrawals", "Revolut Standard: €0/month subscription; separate card delivery and fair-use limits may apply", "Wise: registration €0; international transfer fees vary and were advertised from 0.2%", "Branch banks: often charge a monthly fee unless salary or age conditions are met", "Verify legal entity and deposit-protection information before funding the account"] },
      { heading: "Prepare for identification", paragraphs: ["Banks must verify customers. Accepted identity documents, address evidence, tax-residence questions, and video or in-person procedures vary. Use the bank's current application instructions.", "If an ordinary account application is declined, learn about Germany's statutory basic payment account framework and the conditions described by the Bundesbank and BaFin." ] },
      { heading: "Keep it secure", paragraphs: ["Use a unique password, protect the device and authentication method, and read payment confirmations before approving them. A bank will not need your one-time code to ‘reverse’ a fraud event.", "If you suspect compromise, use the bank's official emergency channel immediately and document what happened."], callout: { title: "Approval means payment", text: "Never approve an authentication request you did not initiate, even when a caller claims to be from the bank.", tone: "warning" } },
    ],
    faqs: [
      { question: "Do I need a German IBAN?", answer: "SEPA rules support eligible euro accounts across participating countries, but a German account can still simplify some local processes. Choose based on practical needs and provider terms." },
      { question: "Can I open an account before registering?", answer: "Requirements vary by provider and applicant. Check the current document list before applying." },
      { question: "What is a basic payment account?", answer: "German law provides a framework for a Basiskonto for eligible consumers. Consult BaFin or the Bundesbank for scope and complaint routes." },
    ], sources: [bafin, bundesbank, n26, revolut, wise], related: ["german-tax-id", "cost-of-living-germany", "first-30-days-germany", "schufa-germany"],
  },
  {
    slug: "deutschlandticket", title: "Deutschlandticket: what it covers and what to check", description: "Understand the nationwide local-transport subscription, its limits, cancellation terms, and the journeys it does not normally cover.", category: "transport", eyebrow: "Transport", updated: "2026-09-23", readingMinutes: 7, featured: true,
    summary: "The Deutschlandticket is a subscription for eligible local and regional public transport across Germany. It is not generally a ticket for long-distance ICE, IC, or EC services, and provider terms matter.",
    takeaways: ["Check the current price and conditions before subscribing.", "Local and regional transport is the core scope.", "Long-distance trains are generally outside the offer.", "Cancellation deadlines and app access depend on the seller."],
    sections: [
      { heading: "Understand the network, not just the name", paragraphs: ["The ticket is designed for participating local and regional services across Germany, including many buses, trams, U-Bahn, S-Bahn, and regional trains. The exact service category matters more than the geographical distance.", "ICE, IC, and EC are generally long-distance products and are normally excluded. Do not board based only on the destination or platform; check the train category in the journey planner." ] },
      { heading: "Know the exact reference prices", paragraphs: ["The Deutschlandticket costs €63 per person and month in 2026. The nationwide Deutschlandsemesterticket is €37.80 per eligible student and month, equivalent to €226.80 for a six-month semester from winter semester 2026/27 at participating institutions.", "Both are personal subscriptions. The semester product is not available simply because somebody is young: the institution must participate and the person must be eligible."], bullets: ["Deutschlandticket: €63/month", "Deutschlandsemesterticket: €37.80/month or €226.80 per six-month semester", "BahnCard 25, second class: €62.90/year", "My BahnCard 25 for eligible travellers under 27: €39.90/year"], callout: { title: "Check the cancellation deadline", text: "If you need the ticket for one month, confirm when and how the chosen provider requires cancellation before you subscribe.", tone: "warning" } },
      { heading: "Use the right app for each journey", paragraphs: ["DB Navigator is the broad starting point for local and long-distance connections, live changes and tickets. Activate the ‘Only D-Ticket connections’ filter when you want routes covered by the Deutschlandticket.", "Also install the local transport association app. In Rhine-Neckar, myVRN covers real-time buses, trams and trains and can show VRNnextbike availability; the nextbike app works across many participating German city systems."], resources: [
        { label: "DB Navigator", url: "https://www.bahn.de/service/mobile/db-navigator", note: "Nationwide planner, tickets, live information and Deutschlandticket filters." },
        { label: "myVRN", url: "https://www.vrn.de/service/apps/companion/index", note: "Official Rhine-Neckar app for Mannheim, Heidelberg and the wider VRN region." },
        { label: "nextbike", url: "https://www.nextbike.de/de/", note: "Bike sharing in participating cities; reference tariff from €1 per 15 minutes." },
        { label: "Local operators", url: "https://www.bahn.de/service/ueber-uns/inside-bahn/maps/verkehrsverbuende-deutschland", note: "Find the responsible transport association for local tickets and carriage rules." },
      ] },
    ],
    faqs: [
      { question: "Can I take an ICE with the Deutschlandticket?", answer: "Generally no. The offer is centred on local and regional transport. Check the specific service and any officially published exception." },
      { question: "Is the ticket valid in every city?", answer: "It is widely valid on participating local and regional services throughout Germany, but check special services and local carriage rules." },
      { question: "Does it cancel automatically?", answer: "Do not assume so. It is a subscription; review the seller's cancellation terms and deadline." },
    ], sources: [db, federalTransport, dbNavigator, nextbike], related: ["first-30-days-germany", "living-mannheim", "best-cities-germany", "cost-of-living-germany"],
  },
  {
    slug: "cost-of-living-germany", title: "Cost of living in Germany: build your own realistic budget", description: "Use a practical budget framework for housing, insurance, transport, food, utilities, and one-off moving costs without relying on misleading averages.", category: "money", eyebrow: "Money", updated: "2026-09-23", readingMinutes: 10, featured: true,
    summary: "Germany does not have one meaningful cost of living. Housing, household type, employment or student status, transport, and insurance create much larger differences than a national average suggests.",
    takeaways: ["Start with the actual housing market in your target area.", "Separate recurring costs from arrival cash needs.", "Model a conservative and a stress case.", "Use official statistics for context, not as a substitute for live quotes."],
    sections: [
      { heading: "Housing sets the shape of the budget", paragraphs: ["Research current listings for homes you could realistically secure—not the median of an entire city. Record cold rent, operating costs, heating setup, electricity, internet, furnishing, deposit, and commute.", "A cheaper home can cost more overall when it creates a long commute or needs separate furnishings. Compare total monthly and initial cash requirements." ] },
      { heading: "Build the recurring baseline", paragraphs: ["Include housing, health-insurance impact, transport, groceries, mobile and internet, broadcasting contribution where applicable, household insurance choices, debt payments, and regular transfers.", "Some payroll deductions happen before net salary reaches you. Do not add them again, but make sure your net estimate is appropriate to your personal circumstances."], bullets: ["Warm rent plus excluded utilities", "Health and other insurance", "Transport", "Food and household goods", "Phone and internet", "Subscriptions and contributions", "Savings and irregular expenses"] },
      { heading: "Add the arrival layer", paragraphs: ["Temporary accommodation, deposits, travel, documents, basic furniture, kitchen items, transport passes, and overlapping rent can create a large first-month requirement even when the recurring budget works.", "Keep an emergency buffer separate from the planned move fund. A job start and first salary payment do not always line up with the date your costs begin." ] },
      { heading: "Use scenarios, not false precision", paragraphs: ["Create a base case from verified quotes, a conservative case with higher housing and travel costs, and a stress case that includes an extended housing search or delayed income. Update the model once you have real bills.", "Online calculators can help structure questions, but tax, insurance, and benefit results require reliable inputs and may need professional advice."], callout: { title: "A budget is a decision tool", text: "Avoid one-number promises. Record the date and source beside every estimate so you know what to refresh.", tone: "note" } },
    ],
    faqs: [
      { question: "How much money do I need per month?", answer: "There is no responsible universal figure. Build a budget from target-area rent, household size, insurance, transport, and your actual commitments." },
      { question: "Which city is cheapest?", answer: "City-level averages hide neighbourhood, quality, and availability. Compare homes you could actually rent and the journey required." },
      { question: "How much should I save before moving?", answer: "Cover travel, temporary housing, deposits, setup costs, ordinary spending, and a delay buffer. The amount depends on your household and certainty of income." },
    ], sources: [stats, consumer], related: ["moving-to-germany", "finding-housing-germany", "german-bank-account", "best-cities-germany"],
  },
  {
    slug: "german-sim-cards", title: "German SIM cards: choose a plan without contract surprises", description: "Compare prepaid and contract mobile plans by network, coverage, data, roaming, identification, and cancellation terms.", category: "daily-life", eyebrow: "Daily life", updated: "2026-09-23", readingMinutes: 7,
    summary: "Choose a German mobile plan by the places you need it to work, the contract commitment, and the complete recurring cost. A large data allowance is not useful on an unsuitable network or inflexible agreement.",
    takeaways: ["Check coverage at home, work, and common journeys.", "Prepaid can reduce commitment during the first weeks.", "Activation requires identity verification.", "Read renewal, price-change, and cancellation terms."],
    sections: [
      { heading: "Start with concrete prepaid options", paragraphs: ["For a newcomer, prepaid is normally the easiest reference point because there is no 24-month commitment. Prices below were checked on 24 September 2026 and are per four weeks, not per calendar month.", "ALDI TALK, Lidl Connect and Penny Mobil each listed an entry package with 25 GB and German all-network calls and SMS for €8.99 per four weeks. Vodafone CallYa Allnet Flat S listed 25 GB for €9.99 per four weeks. Network, speed and promotional data differ, so choose coverage before headline gigabytes."], resources: [
        { label: "ALDI TALK", url: "https://www.alditalk.de/kombi-paket-s", note: "Kombi-Paket S: 25 GB, 5G and all-network flat for €8.99/4 weeks." },
        { label: "Lidl Connect", url: "https://www.lidl.de/c/lidl-connect-smart-s/s10007722", note: "Smart S: 25 GB, 5G and all-network flat for €8.99/4 weeks." },
        { label: "Penny Mobil", url: "https://www.pennymobil.de/", note: "Smart: 25 GB and all-network flat for €8.99/4 weeks." },
        { label: "Vodafone CallYa", url: "https://www.vodafone.de/prepaid/", note: "Allnet Flat S: 25 GB for €9.99/4 weeks at the verification date." },
      ] },
      { heading: "Test the network against your life", paragraphs: ["Use provider coverage maps as a starting point, then ask people in the actual building or area. Indoor coverage and rural routes can differ from a general city-level impression.", "Check 4G and 5G availability, speed restrictions, hotspot rules, EU roaming, international calling, and whether eSIM is supported on your device." ] },
      { heading: "Activate and protect the number", paragraphs: ["Since 1 July 2017, German prepaid providers must verify customer identity before activation. Have an accepted passport or identity card ready and use the provider's own VideoIdent, eID or PostIdent route.", "Protect account login and porting credentials. When changing provider, request number transfer before closing the old service and check whether the plan renews automatically when sufficient prepaid credit is available."], callout: { title: "Use official activation channels", text: "Identity documents are valuable. Verify the provider and web address before starting video or document verification.", tone: "warning" } },
    ],
    faqs: [
      { question: "Can I buy a German SIM before registering?", answer: "Provider requirements vary. Prepaid products still require identity verification, but the accepted documents and address process differ." },
      { question: "Is eSIM always available?", answer: "No. It depends on provider, plan, and device. Confirm support before ordering." },
      { question: "Will EU roaming cover long-term use abroad?", answer: "EU roaming is subject to fair-use conditions. Check the provider's current terms if you spend extended periods outside Germany." },
    ], sources: [consumer, mobileRegulator], related: ["first-30-days-germany", "moving-to-germany", "german-bank-account", "german-supermarkets"],
  },
  {
    slug: "internet-germany", title: "Home internet in Germany: prices, providers, and setup", description: "Compare DSL, cable, fibre and flexible home internet using exact 2026 price examples, contract costs and address availability.", category: "daily-life", eyebrow: "Daily life", updated: "2026-09-24", readingMinutes: 8,
    summary: "Check the exact address before comparing providers: the same company can offer DSL, cable or fibre with different speeds, installation dates and conditions. Compare the full 24-month cost, not only the introductory banner.",
    takeaways: ["Run an address availability check before choosing a tariff.", "Compare regular price, setup, router, shipping and minimum term.", "50–100 Mbit/s is normally enough for one or two people using video calls and streaming.", "Keep a mobile-data backup until the fixed line is active."],
    sections: [
      { heading: "Use exact 2026 offers as reference points", paragraphs: ["At the verification date, Vodafone listed GigaZuhause 50 Cable at €29.99/month with a €49.99 connection charge and €9.99 router shipping, subject to address availability. Its CableMax 1000 reference was €49.99/month plus the same connection charge.", "O2 Home S Flex listed 50 Mbit/s at €24.99/month for the first 12 months and €34.99 afterwards, with a promotional €9.99 connection charge and monthly cancellation. Telekom's 2026 price list put 50 Mbit/s MagentaZuhause M variants at €47.95 or €52.95/month depending on the calling package."], bullets: ["Vodafone 50 Cable reference: €29.99/month + €49.99 connection + €9.99 shipping", "Vodafone CableMax 1000 reference: €49.99/month + €49.99 connection", "O2 Home S Flex 50: €24.99/month for 12 months, then €34.99; promotional connection €9.99", "Telekom MagentaZuhause M 50: €47.95–€52.95/month depending on calling package"], resources: [
        { label: "Vodafone", url: "https://www.vodafone.de/festnetz/kabel-deutschland-internet.html", note: "Cable availability and current 50–1000 Mbit/s offers." },
        { label: "O2 Home Flex", url: "https://www.o2online.de/internet-festnetz/ohne-vertragslaufzeit/", note: "Monthly-cancellable home internet with address-dependent technology." },
        { label: "Telekom", url: "https://www.telekom.de/festnetz/tarife-und-optionen/internet-dsl", note: "DSL and fibre availability, regular prices and product sheets." },
        { label: "1&1", url: "https://dsl.1und1.de/", note: "DSL and fibre alternative; calculate the post-promotion total before ordering." },
      ] },
      { heading: "Choose speed from actual use", paragraphs: ["For one or two people, 50 Mbit/s usually covers browsing, HD streaming and one video call. Choose around 100–150 Mbit/s for several simultaneous streams or regular large downloads; 250 Mbit/s or more mainly helps larger households and heavy parallel use.", "Advertised speed is a maximum. Read the product information sheet for normal and minimum speeds, and prefer an Ethernet test when checking whether the delivered service matches the contract."] },
      { heading: "Check the full contract before ordering", paragraphs: ["Add regular monthly price, all discounted months, connection charge, router rental or purchase, shipping and the minimum term. Confirm whether the landlord or building must approve installation and whether an existing cable-TV arrangement creates a separate charge.", "Ask for the activation date in writing. Until the line works, keep enough prepaid mobile data or choose a cancellable LTE/5G home option rather than relying on an unconfirmed installation date."], callout: { title: "Introductory price is not the monthly budget", text: "Calculate total contract cost divided by the minimum-term months. A low first-year price can hide a much higher second year.", tone: "warning" } },
    ],
    faqs: [
      { question: "How much should home internet cost?", answer: "The 2026 examples on this page put common 50 Mbit/s offers roughly between €29.99 and €52.95 per month before one-off costs, depending on provider, technology and contract structure." },
      { question: "Do I need 1000 Mbit/s?", answer: "Usually not for one person. It mainly reduces large-download time and supports many simultaneous heavy users; reliability and upload speed can matter more." },
      { question: "Can I order before moving in?", answer: "You can check and order for the new address, but coordinate access, activation and any technician appointment with the landlord or previous occupant." },
    ],
    sources: [
      { name: "Vodafone home internet", url: "https://www.vodafone.de/festnetz/kabel-deutschland-internet.html", note: "Primary provider price and contract information" },
      { name: "O2 Home Flex", url: "https://www.o2online.de/internet-festnetz/ohne-vertragslaufzeit/", note: "Primary provider price and flexibility information" },
      { name: "Telekom 2026 price list", url: "https://www.telekom.de/agb/downloads/56068.pdf", note: "Primary provider price list" },
    ],
    related: ["german-sim-cards", "cost-of-living-germany", "finding-housing-germany", "first-30-days-germany"],
  },
  {
    slug: "german-supermarkets", title: "German supermarkets: shopping, Pfand, payment, and labels", description: "A practical first-shop guide to supermarket formats, deposit returns, checkout habits, food labels, and Sunday planning.", category: "daily-life", eyebrow: "Daily life", updated: "2026-09-23", readingMinutes: 7,
    summary: "German grocery shopping is straightforward once you know the store formats, bring-your-own-bag habit, Pfand return system, checkout pace, and limited Sunday opening.",
    takeaways: ["Discount and full-range supermarkets serve different shopping needs.", "Many drink containers carry a refundable deposit.", "Bring bags and pack away from the checkout when possible.", "Plan around Sunday and public-holiday closures."],
    sections: [
      { heading: "Use this practical store ranking", paragraphs: ["For the lowest routine basket, start with ALDI, Lidl, Penny, Netto Marken-Discount or Norma and compare private labels. For a large one-stop shop, Kaufland usually offers more categories. REWE and EDEKA are useful when selection, fresh counters, delivery or a nearby location matters more than the absolute lowest basket.", "dm and Rossmann are often useful for toiletries, baby products and household consumables. Action is not a supermarket: use it for low-cost household goods, cleaning, storage and seasonal items, but not as the basis of a food shop."], bullets: ["Lowest-price starting point: ALDI, Lidl, Penny, Netto, Norma", "Large weekly shop and broad range: Kaufland", "Selection, convenience and service: REWE, EDEKA", "Organic-focused: Bio Company, Alnatura, Denns", "Household and toiletries: dm, Rossmann, Action"] , resources: [
        { label: "ALDI", url: "https://www.aldi-sued.de/", note: "Discount supermarket; compare regional ALDI SÜD or ALDI Nord availability." },
        { label: "Lidl", url: "https://www.lidl.de/", note: "Discount supermarket with nationwide published prices on selected staples." },
        { label: "Kaufland", url: "https://www.kaufland.de/", note: "Large-format supermarket useful for a broad one-stop shop." },
        { label: "REWE", url: "https://www.rewe.de/", note: "Full-range supermarket; online prices can depend on the selected location." },
        { label: "Action", url: "https://www.action.com/de-de/", note: "Non-food discounter for household basics; not a normal grocery supermarket." },
      ] },
      { heading: "Use real staple prices as anchors", paragraphs: ["A useful budget comes from repeatable items, not a vague national basket. Lidl's published January 2026 nationwide references included parboiled rice at €1.39/kg, jasmine rice at €1.99/kg and basmati rice at €2.49/kg. Its November 2025 reference listed one litre of full-fat fresh milk at €0.95 and 250 g of butter at €1.29.", "Treat these as dated anchors, not guaranteed shelf quotes. Fresh food, promotions and regional availability move; compare the unit price printed on the shelf and keep a two-week receipt sample to calculate your own normal basket."], bullets: ["Minimum one-person grocery planning anchor: about €180–€220/month with home cooking", "Normal mixed basket: about €260–€320/month", "Frequent premium, organic or convenience products: €380/month or more", "Always compare €/kg or €/l, not only package price"] },
      { heading: "Use the Pfand system", paragraphs: ["Many beverage containers include a deposit shown separately from the shelf price. Return eligible containers through the store machine or return point and take the receipt to the checkout.", "Return systems distinguish container types and participating formats. Look for the deposit markings and follow the machine instructions rather than placing deposit containers in household recycling." ] },
      { heading: "At the checkout", paragraphs: ["Place a divider after your shopping, keep payment ready, and move purchases into the packing area or trolley promptly. Bring reusable bags or expect to pay for bags.", "Card acceptance is common but not universal across every small shop or market. Keeping a modest alternative payment method can be practical." ] },
      { heading: "Plan the week", paragraphs: ["Most ordinary supermarkets close on Sundays and public holidays, with limited exceptions such as some station or airport outlets. Check local hours rather than assuming a national schedule.", "Learn common label terms for allergens, ingredients, best-before dates, use-by dates, and unit pricing. Ask staff when a food-safety label is unclear."], callout: { title: "Best-before is not use-by", text: "German labels distinguish quality guidance from safety-related use-by dates. Follow the product's exact wording and storage instructions.", tone: "note" } },
    ],
    faqs: [
      { question: "Are Aldi and Lidl always cheapest?", answer: "They often compete strongly on price, but the lowest total depends on your basket, local stores, and promotions." },
      { question: "Can I return every bottle anywhere?", answer: "Not always. Return obligations and machine acceptance depend on container and retailer. Use the deposit markings and store guidance." },
      { question: "Where can I shop on Sunday?", answer: "Options are limited and local. Some stations, airports, bakeries, or designated openings may be available; check current local information." },
    ], sources: [consumer, { name: "Lidl — 2026 staple prices", url: "https://unternehmen.lidl.de/pressreleases/2026/260102_lidl_pi_preissenkung-grundnahrungsmittel", note: "Primary dated price references" }], related: ["cost-of-living-germany", "german-bank-account", "first-30-days-germany", "german-sim-cards"],
  },
];
