import type { Guide } from "@/lib/types";

const makeIt = { name: "Make it in Germany", url: "https://www.make-it-in-germany.com/en/", note: "Official federal portal for international skilled workers" };
const bmi = { name: "Federal Ministry of the Interior — registration", url: "https://www.bmi.bund.de/EN/topics/administrative-reform/passports-identity-cards/passports-identity-cards-node.html", note: "Federal administrative context" };
const service = { name: "Germany's federal service portal", url: "https://verwaltung.bund.de/portal/EN", note: "Find responsible authorities and public services" };
const taxOffice = { name: "Federal Central Tax Office", url: "https://www.bzst.de/EN/Private_individuals/Tax_identification_number/tax_identification_number_node.html", note: "Official Tax ID information" };
const registrationAct = { name: "Federal Registration Act", url: "https://www.gesetze-im-internet.de/englisch_bmg/englisch_bmg.html", note: "Official text of the national registration deadline and temporary-stay exceptions" };

export const moveAndAdminGuides: Guide[] = [
  {
    slug: "moving-to-germany",
    title: "Moving to Germany: a practical planning guide",
    description: "Plan your move to Germany in the right order—from eligibility and documents to housing, insurance, registration, and work.",
    category: "moving-to-germany",
    eyebrow: "Moving",
    updated: "2026-09-24",
    readingMinutes: 11,
    featured: true,
    summary: "A successful move is mostly about sequencing. Confirm your legal route first, then connect housing, insurance, registration, work, and finances around the dates that each step becomes possible.",
    takeaways: ["Your nationality and purpose of stay determine the immigration route—not generic expat advice.", "Registrable accommodation is a key dependency for several later steps.", "Bring original documents and keep secure digital copies.", "Use official sources for current requirements and appointment rules."],
    sections: [
      { heading: "1. Confirm your route before making commitments", paragraphs: ["Start with your nationality, reason for moving, intended work or study, and expected length of stay. EU freedom-of-movement rules and the routes available to non-EU nationals are not interchangeable. A job offer, university admission, self-employment plan, or family relationship may each lead to different evidence and conditions.", "Use an official federal portal or the German mission responsible for your place of residence. Check whether you need approval before travel and whether your planned work is permitted from day one."], callout: { title: "Avoid an expensive mismatch", text: "Do not sign a long lease, resign from work, or book non-refundable travel until the legal route and realistic timeline are clear.", tone: "warning" } },
      { heading: "2. Build one document system", paragraphs: ["Collect valid identity documents, civil-status records where relevant, work or study evidence, insurance records, qualifications, and housing paperwork. Requirements vary by procedure; the goal is not to carry every document everywhere, but to know where the authoritative original is.", "Create an encrypted digital folder with clear filenames and keep physical originals separate from everyday luggage. Check in advance whether a particular authority requires a certified copy or translation."], bullets: ["Passport or national identity card", "Employment, study, or self-employment evidence", "Insurance evidence", "Civil-status documents when relevant", "Qualification records", "Proof of accommodation"] },
      { heading: "3. Plan housing as infrastructure", paragraphs: ["Your first address affects registration, post, banking, and many applications. Confirm in writing whether you can register at the accommodation and whether the provider will issue a Wohnungsgeberbestätigung after move-in.", "Temporary accommodation can be useful, but do not assume a hotel, short-term room, or sublet automatically supports registration. Ask explicitly before paying."], callout: { title: "One useful question", text: "Ask: ‘Can I complete Anmeldung at this address, and will you provide the Wohnungsgeberbestätigung?’", tone: "note" } },
      { heading: "4. Prepare the first-month essentials", paragraphs: ["Map health insurance, address registration, your Tax ID, a payment account, mobile connectivity, and the route to work or study. Some tasks are sequential, while others can run in parallel.", "Keep a small arrival buffer. Appointments, post, deposits, temporary accommodation, and initial purchases can create timing and cash-flow pressure even when the move is well planned."], bullets: ["Book flexible temporary plans where possible", "Research the municipal registration process", "Know how you will access healthcare", "Keep more than one payment method", "Put your name on the mailbox once you move in"] },
    ],
    faqs: [
      { question: "Can I move first and arrange everything later?", answer: "That depends on your nationality and purpose of stay. Some people can enter and complete later steps in Germany; others need the correct visa or approval before travelling. Check the official route that applies to you." },
      { question: "Do I need a permanent apartment before arrival?", answer: "Not always, but you should understand whether your initial accommodation allows address registration. This can affect later administrative tasks." },
      { question: "Which city should I choose?", answer: "Compare work or study access, realistic housing options, transport, budget, language needs, and your support network. A famous city is not automatically the best operational fit." },
    ],
    sources: [makeIt, service],
    related: ["first-30-days-germany", "finding-housing-germany", "german-health-insurance", "cost-of-living-germany"],
  },
  {
    slug: "first-30-days-germany",
    title: "Your first 30 days in Germany",
    description: "A calm, dependency-aware checklist for registration, insurance, Tax ID, banking, connectivity, transport, and work after arrival.",
    category: "moving-to-germany",
    eyebrow: "Arrival checklist",
    updated: "2026-09-23",
    readingMinutes: 9,
    featured: true,
    summary: "Your first month is easier when you separate urgent legal or health tasks from conveniences. Start with your right to stay, safe accommodation, insurance, and local registration; then complete the systems that depend on them.",
    takeaways: ["The standard Anmeldung deadline is 14 days after moving into a dwelling; statutory temporary-stay exceptions exist.", "Registration depends on having moved into an address and receiving the accommodation-provider confirmation.", "Your Tax ID normally follows registration; protect it as a long-term identifier.", "Keep a written record of appointments, submissions, and documents sent."],
    sections: [
      { heading: "Days 1–3: make the basics reliable", paragraphs: ["Confirm you can access your accommodation, receive post, use a working phone connection, and pay for essentials. Put your name on the mailbox if appropriate. If your health coverage requires activation or an employer or university needs evidence, address that immediately.", "Review the conditions attached to your immigration status before starting work. Arrival itself does not automatically grant every form of employment."], bullets: ["Safe access to accommodation", "Mailbox and reliable contact details", "Health coverage pathway", "Backup payment method", "Copies of key documents"] },
      { heading: "Days 1–14: handle address registration", paragraphs: ["The standard national deadline is two weeks after moving into a dwelling. Check the registration process on your municipality's official website. You will generally need valid identification and a Wohnungsgeberbestätigung from the accommodation provider. The exact booking system and accepted documents are local.", "Keep the confirmation you receive. It may be useful for banking, insurance, immigration, and other records. The Federal Registration Act has exceptions for certain temporary stays, including people already registered in Germany who use another dwelling for no longer than six months."], callout: { title: "The deadline is national; the process is local", text: "Book or follow the municipality's published route as early as possible and keep evidence of attempts if appointments are unavailable.", tone: "note" } },
      { heading: "Weeks 1–2: connect the systems", paragraphs: ["Once registered, watch the mailbox for official post, including your Tax ID when issued. Provide employers or institutions only the identifiers they legitimately require and store originals securely.", "Set up a suitable bank account and mobile plan based on your needs, not a rushed comparison. Check fees, identification method, customer support, and cancellation terms."], bullets: ["Tax ID correspondence", "Bank or payment account", "Mobile connection", "Employer or university records", "Residence appointment where applicable"] },
      { heading: "Weeks 3–4: stabilise daily life", paragraphs: ["Learn your local transport system, waste separation rules, essential shops, medical access, and emergency contacts. Review your budget using actual spending rather than pre-move estimates.", "Set one monthly admin session. Germany generates important physical and digital correspondence; reading it early is easier than fixing missed deadlines later."] },
    ],
    faqs: [
      { question: "What should I do first after arriving?", answer: "Secure accommodation access, health coverage, reliable communication, and clarity about your legal status. Then follow the municipal registration process." },
      { question: "What if I cannot get an Anmeldung appointment immediately?", answer: "Use your municipality's official guidance, retain evidence of attempts where useful, and avoid relying on another city's procedure. Do not fabricate an address or document." },
      { question: "Should I buy every service in the first week?", answer: "No. Prioritise necessities and commitments with deadlines. Compare longer-term contracts once your address, budget, and likely length of stay are clearer." },
    ],
    sources: [registrationAct, service, makeIt],
    related: ["anmeldung-germany", "wohnungsgeberbestaetigung", "german-tax-id", "german-bank-account"],
  },
  {
    slug: "anmeldung-germany",
    title: "Anmeldung in Germany: address registration explained",
    description: "Understand what Anmeldung is, who handles it, what to prepare, and what happens after you register your German address.",
    category: "bureaucracy",
    eyebrow: "Bureaucracy",
    updated: "2026-09-24",
    readingMinutes: 8,
    featured: true,
    summary: "Anmeldung is the registration of your place of residence with the local authority after you move into an address. The standard deadline is 14 days after moving in and the service is free, while appointment systems and document details vary by municipality.",
    takeaways: ["The standard deadline is 14 days after moving into a dwelling.", "The standard registration service is free.", "The Wohnungsgeberbestätigung is separate from your rental contract.", "Use the official website for your municipality and store the confirmation safely."],
    sections: [
      { heading: "What Anmeldung does", paragraphs: ["Address registration records your residence in the local population register. It is not a visa, residence permit, rental approval, or Tax ID application, although it can connect to later processes.", "When you move within Germany, you normally register the new address; the competent office handles the record. If you leave Germany without keeping a residence, a separate deregistration process may apply."], callout: { title: "Not an immigration decision", text: "Completing Anmeldung does not create a right to live or work in Germany. Immigration status is a separate matter.", tone: "warning" } },
      { heading: "The exact deadline and the exceptions", paragraphs: ["Section 17 of the Federal Registration Act sets the standard deadline at two weeks after moving into a dwelling. The standard registration service costs €0. Make the appointment or use the municipality's published submission route promptly after moving in.", "Section 27 contains temporary-stay exceptions. If you are already registered in Germany and use another dwelling for no longer than six months, you generally do not register it. If you normally live abroad and are not registered in Germany, the duty generally arises once the stay exceeds three months. Check the official wording when an exception may apply."], callout: { title: "14 days, not 14 working days", text: "The law says two weeks. Local appointment availability does not change the statutory wording, so follow the municipality's official instructions and retain evidence of timely attempts where useful.", tone: "note" } },
      { heading: "Prepare for the appointment", paragraphs: ["Check the exact service page for your municipality. Typical core items include valid identification and the accommodation provider's confirmation. Additional evidence can depend on the people registering and the local procedure.", "Complete forms accurately and keep names consistent with identity documents. If you need an interpreter or accessibility support, investigate the city's arrangements before the appointment."], bullets: ["Official booking confirmation", "Valid identity document", "Completed local form if required", "Wohnungsgeberbestätigung", "Additional civil-status evidence only when the official checklist requires it"] },
      { heading: "At and after registration", paragraphs: ["Review the details on the registration confirmation before leaving if possible. Your name and address should match the documents you use elsewhere.", "After registration, official correspondence may arrive by post. Make sure your name is visible on the mailbox and do not discard letters you do not recognise before understanding them."], bullets: ["Secure the registration confirmation", "Monitor the mailbox", "Update relevant providers", "Keep the Tax ID letter when it arrives"] },
    ],
    faqs: [
      { question: "Is Anmeldung the same everywhere?", answer: "The underlying duty is national, but appointments, forms, and practical document checks are handled locally. Always consult your municipality." },
      { question: "How many days do I have for Anmeldung?", answer: "The standard rule is two weeks—14 calendar days—after moving into a dwelling. Federal law contains exceptions for certain temporary stays, so check §27 if your stay is temporary." },
      { question: "How much does Anmeldung cost?", answer: "The standard address-registration service is free. A municipality may charge separately for optional certificates or different services." },
      { question: "Is a rental contract enough?", answer: "The official process generally distinguishes the contract from the Wohnungsgeberbestätigung. Follow the current local checklist." },
      { question: "Does Anmeldung give me a residence permit?", answer: "No. Address registration and immigration permission are separate processes." },
    ],
    sources: [registrationAct, service, bmi],
    related: ["wohnungsgeberbestaetigung", "german-tax-id", "first-30-days-germany", "finding-housing-germany"],
  },
  {
    slug: "wohnungsgeberbestaetigung",
    title: "Wohnungsgeberbestätigung: the document you need for Anmeldung",
    description: "A clear guide to Germany's accommodation-provider confirmation: what it proves, who issues it, and common mistakes to avoid.",
    category: "bureaucracy",
    eyebrow: "Bureaucracy",
    updated: "2026-09-23",
    readingMinutes: 6,
    summary: "The Wohnungsgeberbestätigung confirms that you moved into an address. It is issued by the person or organisation providing the accommodation and is used for address registration.",
    takeaways: ["It confirms move-in; it is not the same as a rental contract.", "Ask about it before committing to accommodation.", "The issuer must provide accurate details.", "Use your municipality's current template or requirements."],
    sections: [
      { heading: "What the document confirms", paragraphs: ["The confirmation links the person moving in, the address, the move-in date, and the accommodation provider. Its purpose is specific: supporting the registration of residence.", "A booking receipt, payment confirmation, or ordinary lease may contain overlapping information but does not automatically replace the required confirmation." ] },
      { heading: "Who provides it", paragraphs: ["The issuer may be the property owner, a property manager acting for the owner, or a main tenant legitimately providing a sublet. The correct issuer depends on the accommodation arrangement.", "If a sublet is involved, clarify that the arrangement is permitted and that the responsible person will issue the confirmation. Do not accept altered or fabricated paperwork."], callout: { title: "Ask before you pay", text: "If registration is important to your move, make the provider's willingness and ability to issue the document part of your housing checks.", tone: "warning" } },
      { heading: "Check it before your appointment", paragraphs: ["Compare the spelling of names, full address, move-in date, and provider details with your documents. Ask for corrections before the registration appointment if something is wrong.", "Keep a copy with your lease and registration confirmation. If the authority uses its own form, download the current version directly from the municipal website." ] },
    ],
    faqs: [
      { question: "Can a landlord refuse to provide it?", answer: "Accommodation providers have legal responsibilities, but the correct response depends on the facts. Start with the municipal authority's guidance and seek qualified advice for a dispute." },
      { question: "Can a main tenant issue it for a sublet?", answer: "This can be possible when the main tenant is legitimately providing the accommodation. The sublet itself should be authorised where required." },
      { question: "Can I use an old confirmation after moving?", answer: "The document should represent your actual move into the address being registered. Do not reuse inaccurate paperwork." },
    ],
    sources: [service, bmi],
    related: ["anmeldung-germany", "renting-in-germany", "finding-housing-germany", "german-tax-id"],
  },
  {
    slug: "german-tax-id",
    title: "German Tax ID (Steuer-ID): what it is and how to find it",
    description: "Learn what Germany's personal Tax ID is, how it differs from other tax numbers, and what to do if you have not received it.",
    category: "bureaucracy",
    eyebrow: "Bureaucracy",
    updated: "2026-09-23",
    readingMinutes: 7,
    featured: true,
    summary: "The Steueridentifikationsnummer is a personal identification number used by the German tax administration. It is designed to remain with you; it is not the same as a tax number assigned for a particular tax matter.",
    takeaways: ["Keep the Tax ID letter permanently and securely.", "Do not confuse the Steuer-ID with a Steuernummer or VAT identifier.", "Employers may need it for payroll.", "Use the Federal Central Tax Office process to request it again if necessary."],
    sections: [
      { heading: "Which number people mean", paragraphs: ["In everyday conversation, ‘tax number’ can refer to different identifiers. The personal Tax ID identifies an individual in the tax system. A Steuernummer can be associated with a tax office and a tax case, while business and VAT contexts can involve other identifiers.", "Check the label on the document instead of relying on the number's position or length alone."], callout: { title: "Share carefully", text: "A Tax ID is sensitive personal information. Give it only to organisations with a legitimate reason, such as your employer or tax authority.", tone: "warning" } },
      { heading: "How you receive it", paragraphs: ["For a person registering a German address for the first time, the Tax ID is generally communicated after the registration information reaches the tax administration. Delivery and timing can vary, so ensure your mailbox is correctly labelled.", "If you already received a Tax ID in the past, the same identifier continues to apply. Moving or leaving Germany does not create a new personal Tax ID." ] },
      { heading: "If the letter does not arrive", paragraphs: ["First check that the name on your mailbox and registration record is correct. If sufficient time has passed, use the Federal Central Tax Office's official information and request channel rather than paying an unofficial intermediary.", "An employer can explain its temporary payroll handling, but cannot issue the Tax ID. For personal tax consequences, consult the responsible tax authority or a qualified adviser." ] },
    ],
    faqs: [
      { question: "Is the Steuer-ID the same as the Steuernummer?", answer: "No. The Steuer-ID identifies an individual, while a Steuernummer is used for particular tax-administration contexts." },
      { question: "Does my Tax ID change when I move?", answer: "The personal Tax ID is intended to remain the same. Update your address with the relevant organisations, but do not apply for a second ID." },
      { question: "Can I work while waiting for it?", answer: "Discuss payroll setup with the employer. The answer can depend on timing and circumstances; the employer and tax authority can explain the applicable process." },
    ],
    sources: [taxOffice, service],
    related: ["anmeldung-germany", "first-30-days-germany", "working-in-germany", "german-bank-account"],
  },
];
