import type { Guide } from "@/lib/types";

const servicePortal = { name: "Federal service portal", url: "https://verwaltung.bund.de/", note: "Official starting point for public services and responsible authorities" };
const makeIt = { name: "Make it in Germany", url: "https://www.make-it-in-germany.com/en/", note: "Official federal portal for international workers" };

export const newcomerReferenceGuides: Guide[] = [
  {
    slug: "german-documents-explained",
    title: "German documents explained: what they are and what to do next",
    description: "Plain-language explanations of the German documents newcomers see most often, including Anmeldung, Tax ID, payslips, residence permits, Schufa and health-insurance letters.",
    category: "bureaucracy",
    eyebrow: "Documents without the jargon",
    updated: "2026-09-25",
    readingMinutes: 10,
    featured: true,
    summary: "A German document is easier to handle once you know who created it, what it proves, where you will need it and whether it has a deadline. Use the German name when contacting an authority, but keep this plain-language meaning beside it.",
    takeaways: ["Keep the full document, not only a photo of the first page.", "Match the sender, reference number and deadline before replying.", "Do not send original identity documents unless an official process explicitly requires it.", "Ask the sender when a letter is unclear or the facts are wrong."],
    sections: [
      { heading: "Anmeldebestätigung or Meldebestätigung", paragraphs: ["This is the confirmation that your address registration (Anmeldung) was recorded. You normally receive it from the local registration office after the appointment or digital process.", "Keep it with your housing records. Banks, employers, residence procedures and other services may ask for proof of registration. If the address or name is wrong, contact the registration office."], bullets: ["Sent by: local registration office", "Proves: your registered address", "Next step: check every personal detail and store it safely"] },
      { heading: "Wohnungsgeberbestätigung", paragraphs: ["This is the move-in confirmation from the accommodation provider, often the landlord or property manager. It is not the rental contract. You usually need it for Anmeldung.", "Ask for it around move-in and check that the address, move-in date and names are correct. The standard Anmeldung deadline is 14 days after moving in, subject to statutory exceptions."], bullets: ["Sent by: landlord, owner or responsible accommodation provider", "Used for: Anmeldung", "Next step: take it to the registration process with the required identity documents"] },
      { heading: "Steuer-ID", paragraphs: ["The Steueridentifikationsnummer is your permanent 11-digit German tax identification number. It is normally issued after registration and stays with you for life; it is not the same as a business tax number.", "Give it to payroll when requested and keep it private. If the letter does not arrive, use the Federal Central Tax Office's official retrieval route rather than paying an intermediary."], resources: [{ label: "Request your Tax ID", url: "https://www.bzst.de/EN/Private_individuals/Tax_identification_number/tax_identification_number_node.html", note: "Official Federal Central Tax Office information and retrieval route." }] },
      { heading: "Sozialversicherungsausweis", paragraphs: ["This record contains your German social-insurance number. Your health insurer or pension-insurance process normally creates the number when you first enter covered employment.", "Your employer needs the number for social-insurance reporting. Check the spelling of your name and date of birth, then keep it with your employment records."], resources: [{ label: "German Pension Insurance", url: "https://www.deutsche-rentenversicherung.de/DRV/EN/Home/home_node.html", note: "Official information about German pension and social-insurance records." }] },
      { heading: "Gehaltsabrechnung", paragraphs: ["This is your payslip. It shows gross pay, deductions, taxes, social-insurance contributions and the net amount transferred. The layout varies, but the pay period and totals should always reconcile with your contract and bank payment.", "Compare your name, tax class, health insurer, working time and gross salary. Ask payroll quickly if something is missing or different from the contract."], bullets: ["Brutto: gross pay before deductions", "Netto: amount after deductions", "Lohnsteuer: wage tax", "Sozialversicherung: statutory social-insurance deductions"] },
      { heading: "Aufenthaltstitel", paragraphs: ["This is the residence title for a non-EU route. The card or document states the legal basis, validity and any work-related conditions. It is not interchangeable with an entry visa.", "Read the expiry date and the Nebenbestimmungen (additional conditions). Start any renewal early enough for your local authority's processing time."], resources: [{ label: "BAMF residence information", url: "https://www.bamf.de/EN/Themen/MigrationAufenthalt/migrationaufenthalt-node.html", note: "Official residence and migration overview." }] },
      { heading: "Versicherungsbescheinigung", paragraphs: ["This is an insurance certificate. For health insurance, it confirms cover or membership details, but the exact document needed by a university, employer or authority depends on that process.", "Check the insurer, start date and member number. For university enrolment, ask the university whether it needs a digital insurer notification rather than a paper certificate."], resources: [{ label: "Health insurance overview", url: "https://www.make-it-in-germany.com/en/living-in-germany/money-insurance/health-insurance", note: "Official newcomer overview of health-insurance routes." }] },
      { heading: "SCHUFA-Auskunft", paragraphs: ["A SCHUFA report is credit-related information from a private credit bureau, not a government document. Landlords may request a version intended for third parties, but you should avoid sharing unnecessary account-level data.", "Order from the provider you intend to use, understand which version you are buying and redact unrelated sensitive information where appropriate."], resources: [{ label: "SCHUFA", url: "https://www.schufa.de/en/", note: "Provider information about reports, data access and corrections." }] },
      { heading: "Mietvertrag", paragraphs: ["This is your rental agreement. It should identify the parties, dwelling, rent components, deposit, start date and important rules. Warmmiete does not always include electricity, internet or every operating cost.", "Read every annex before signing. Verify the contractual party and property independently, and never transfer money only because a PDF looks official."], resources: [{ label: "Consumer Centre housing guidance", url: "https://www.verbraucherzentrale.de/wissen/umwelt-haushalt/wohnen", note: "Independent consumer information about renting and household contracts." }] },
    ],
    faqs: [
      { question: "Should I carry these documents every day?", answer: "Usually no. Keep secure originals at home and carry only what the specific appointment or situation requires." },
      { question: "What if the name or date is wrong?", answer: "Contact the organisation that issued the document. Do not silently reuse incorrect data across later applications." },
      { question: "Can I send a document by email?", answer: "Only use the channel requested by the verified recipient. Remove unrelated sensitive pages or fields when they are not required." },
    ],
    sources: [servicePortal, makeIt, { name: "Federal Registration Act §17", url: "https://www.gesetze-im-internet.de/bmg/__17.html", note: "Official registration deadline" }],
    related: ["anmeldung-germany", "german-tax-id", "schufa-germany", "first-30-days-germany"],
  },
  {
    slug: "newcomer-faq-germany",
    title: "Germany newcomer FAQ: direct answers to everyday questions",
    description: "Direct answers about Anmeldung, banking, housing, work, transport, healthcare and the first weeks in Germany.",
    category: "moving-to-germany",
    eyebrow: "Quick answers",
    updated: "2026-09-25",
    readingMinutes: 12,
    summary: "Start here when you need a short answer and a next step. German rules depend on status and location, so each answer tells you what is generally true and what you should verify.",
    takeaways: ["Use the answer to choose your next action, not as a substitute for an authority.", "City offices and appointment systems vary.", "A German word can describe a process, document or office—check which one is meant.", "For money and contracts, compare total cost and cancellation terms."],
    sections: [
      { heading: "Your first days", paragraphs: ["Can you start working before Anmeldung? Your right to work comes from citizenship or residence status, not from Anmeldung alone. An employer can still need your address, insurance and payroll details, so confirm onboarding directly.", "What should you do first after arrival? Make your name visible on the mailbox, collect the Wohnungsgeberbestätigung, secure health cover, start Anmeldung and keep a record of every appointment and submission.", "How long can you stay without registering? The standard rule is Anmeldung within 14 days after moving into a dwelling. Specific temporary-stay exceptions exist, so check §27 of the Federal Registration Act if your stay is short." ] },
      { heading: "Housing and money", paragraphs: ["Can you open a bank account before Anmeldung? Sometimes. Provider document and address rules differ. N26, Revolut, Wise and Trade Republic can be useful comparisons, but eligibility, deposits, support, fees and account features are not identical.", "How much money should you bring? Add deposit, first rent, travel, basic furniture, food, transport and a buffer for delayed salary or reimbursements. Use the moving and cost tools with your actual rent rather than a national average.", "Can a landlord ask for SCHUFA? It is common in the private market, but share only the suitable report and avoid unnecessary account data. A SCHUFA report does not replace independent verification of the listing and landlord."], resources: [{ label: "Cost-of-living calculator", url: "/tools/cost-of-living", note: "Build a monthly budget from your own rent." }, { label: "Rental scam checklist", url: "/tools/rental-scam-checker", note: "Review warning signs before paying or sharing documents." }] },
      { heading: "Work and payroll", paragraphs: ["Do you need a German bank account for work? A SEPA euro account should generally be usable, but a German IBAN can simplify some local processes. Ask payroll which payment details it accepts rather than assuming.", "What is your Tax ID? It is a permanent 11-digit personal tax identifier, normally sent after registration. It is different from a Steuernummer used in tax administration or self-employment.", "What does an employer normally ask for? Expect identity and work-authorisation evidence, address and contact details, Tax ID, social-insurance number if one exists, health insurer, bank details and contract-specific qualifications." ] },
      { heading: "Transport and daily life", paragraphs: ["Can you use an ICE with the Deutschlandticket? Normally no: ICE, IC and EC are long-distance products. The 2026 Deutschlandticket is €63 per month for participating local and regional transport.", "Is the student ticket automatic? No. The Deutschlandsemesterticket is €37.80 per month (€226.80 for six months) from winter semester 2026/27, but the institution must participate and eligibility and payment are handled locally.", "Do shops close on Sundays? Most ordinary shops do. Some stations, airports, bakeries and designated local openings are exceptions; check the exact location and date." ] },
      { heading: "Health and emergencies", paragraphs: ["Do you need health insurance from day one? Germany requires health cover, but the route depends on work, study, family and residence status. Confirm the effective start date and accepted proof before relying on a card or application receipt.", "Where do you go when a doctor is closed? Call 116117 for urgent, non-life-threatening medical help. Call 112 for life-threatening emergencies. For a pharmacy, search the official local emergency pharmacy service."], resources: [{ label: "Medical on-call service", url: "https://www.116117.de/de/englisch.php", note: "Official 116117 information in English." }, { label: "Emergency guide", url: "/emergency", note: "Save the key numbers and what each service is for." }] },
    ],
    faqs: [
      { question: "Can I start working before Anmeldung?", answer: "Possibly, if your citizenship or residence status permits work. Anmeldung is not the source of work permission, but the employer may need registration and payroll details." },
      { question: "Can I open a bank account before Anmeldung?", answer: "Some providers allow it for some applicants; others require German address evidence. Check the current document list for your nationality and address situation." },
      { question: "How long do I have to complete Anmeldung?", answer: "The standard deadline is 14 days after moving into a dwelling, with statutory exceptions for some temporary stays." },
      { question: "Can I use ICE trains with the Deutschlandticket?", answer: "Generally no. Use local and regional services and verify the exact train category in the journey planner." },
      { question: "What happens if I lose my Tax ID?", answer: "Use the official Federal Central Tax Office retrieval route. The number does not change because the letter was lost." },
      { question: "Do I need a German phone number?", answer: "It is not universally mandatory, but it simplifies appointment calls, delivery updates, employer contact and two-factor verification." },
      { question: "Is private health insurance cheaper?", answer: "A starting premium alone is not enough to answer. Eligibility, age, health, family coverage, long-term costs and return to statutory insurance all matter." },
      { question: "Can I live in one city and register in another?", answer: "You register the dwelling where you actually live. Do not use an address only for paperwork." },
    ],
    sources: [servicePortal, makeIt, { name: "Federal Registration Act", url: "https://www.gesetze-im-internet.de/bmg/", note: "Official registration law" }, { name: "Deutsche Bahn Deutschlandticket FAQ", url: "https://www.bahn.de/faq/gk/angebot/zeitkarten/deutschland-ticket", note: "Official scope and price information" }],
    related: ["german-documents-explained", "first-30-days-germany", "cost-of-living-germany", "deutschlandticket"],
  },
];
