import { practicalSystemsGuides } from "@/lib/content/guides/practical-systems";
import type { Guide } from "@/lib/types";
import type { Locale } from "@/lib/platform-data";

export type PracticalGuideKey = "sickLeave" | "doctor" | "payslip";

export const practicalGuideSlugs: Record<PracticalGuideKey, Record<"en"|"es"|"de"|"fr", string>> = {
  sickLeave: { en: "sick-leave-germany", es: "baja-medica-alemania", de: "krankschreibung-deutschland", fr: "arret-maladie-allemagne" },
  doctor: { en: "finding-doctor-germany", es: "encontrar-medico-alemania", de: "arzt-finden-deutschland", fr: "trouver-medecin-allemagne" },
  payslip: { en: "german-payslip-explained", es: "nomina-alemana-explicada", de: "gehaltsabrechnung-erklaert", fr: "fiche-paie-allemagne" },
};

const byEnglishSlug = new Map(practicalSystemsGuides.map((guide) => [guide.slug, guide]));
const englishGuide: Record<PracticalGuideKey, Guide> = {
  sickLeave: byEnglishSlug.get("sick-leave-germany")!,
  doctor: byEnglishSlug.get("finding-doctor-germany")!,
  payslip: byEnglishSlug.get("german-payslip-explained")!,
};

const es: Record<PracticalGuideKey, Guide> = {
  sickLeave: {
    ...englishGuide.sickLeave,
    slug: practicalGuideSlugs.sickLeave.es,
    title: "Baja médica en Alemania en 2026: eAU, plazos y salario",
    description: "Cómo funcionan la Krankmeldung y la baja médica electrónica en Alemania en 2026, cuándo avisar a la empresa, cuándo necesitas justificante médico y qué significa la regla de las seis semanas.",
    eyebrow: "Guía práctica de trabajo",
    summary: "Si estás demasiado enfermo para trabajar en Alemania, hay dos obligaciones distintas: avisar a tu empresa sin demora y obtener confirmación médica cuando corresponda. Para la mayoría de trabajadores con seguro público, el justificante se gestiona mediante el sistema eAU en lugar de entregarse en papel.",
    takeaways: [
      "Debes informar a tu empresa de la incapacidad para trabajar y de su duración prevista sin demora innecesaria.",
      "Con la regla vigente, normalmente se necesita confirmación médica si la incapacidad dura más de tres días naturales, aunque la empresa puede exigirla antes.",
      "Para la mayoría de trabajadores con seguro público, la consulta envía la eAU a la aseguradora y la empresa consulta los datos electrónicamente.",
      "El mantenimiento del salario por parte de la empresa puede alcanzar, por regla general, hasta seis semanas si se cumplen los requisitos legales.",
      "A 8 de octubre de 2026, el plan político anunciado para exigir justificante desde el primer día todavía no ha sustituido la norma vigente."
    ],
    sections: [
      { heading:"Paso 1: avisa primero a la empresa", paragraphs:["La baja médica no sustituye el aviso básico a tu empresa. El §5 de la Entgeltfortzahlungsgesetz exige comunicar sin demora que no puedes trabajar y cuánto se espera que dure la ausencia. En la práctica, utiliza el canal que haya fijado la empresa: responsable, RR. HH., teléfono, app o correo.","No esperes a tener la cita médica para comunicar la ausencia. La empresa necesita saber que no trabajarás aunque la confirmación médica llegue después por vía electrónica."], bullets:["Comunica la ausencia en cuanto sepas que no puedes trabajar.","Indica la duración prevista si la conoces.","Respeta cualquier regla interna más estricta de tu contrato o empresa."], callout:{title:"Regla vigente en octubre de 2026",text:"El Gobierno federal ha anunciado planes para endurecer la obligación de justificante, pero su propia información de julio de 2026 indica que las reglas actuales siguen vigentes hasta que esos cambios se apliquen.",tone:"note"} },
      { heading:"Paso 2: cuándo necesitas confirmación médica", paragraphs:["Con la regla legal actual, si la incapacidad dura más de tres días naturales, normalmente debe existir confirmación médica como muy tarde el siguiente día laborable. La empresa puede exigirla antes, incluso desde el primer día.","Por eso dos trabajadores de empresas distintas pueden tener plazos prácticos diferentes. Revisa el contrato, el convenio y la política interna en lugar de asumir que siempre dispones de tres días sin documentación."], bullets:["Regla legal básica: más de tres días naturales activa la obligación de confirmación médica.","La empresa puede exigir el justificante antes.","Si la enfermedad se prolonga más de lo certificado, necesitas una nueva determinación médica."] },
      { heading:"Cómo funciona la eAU con el seguro público", paragraphs:["Para empleados con seguro médico público, la entrega en papel a la empresa se ha sustituido en gran medida por la elektronische Arbeitsunfähigkeitsbescheinigung (eAU). La consulta transmite los datos a la aseguradora y la empresa obtiene electrónicamente la información necesaria.","La eAU elimina normalmente la entrega del papel, pero no la obligación de avisar a la empresa. Guarda la información o justificante que recibas para tus propios registros.","En algunas excepciones, como ciertos casos de seguro privado, médicos fuera de la asistencia concertada o empleos en hogares privados, pueden seguir aplicándose otros procedimientos."], resources: englishGuide.sickLeave.sections[2].resources },
      { heading:"Qué significa realmente la regla de seis semanas", paragraphs:["El §3 de la Entgeltfortzahlungsgesetz prevé el mantenimiento del salario por la empresa durante hasta seis semanas cuando el trabajador no puede trabajar por enfermedad, sin culpa propia y se cumplen los requisitos legales.","No interpretes 'seis semanas' como seis semanas nuevas automáticas para cada ausencia. Las recaídas por la misma enfermedad y situaciones laborales especiales pueden modificar el cálculo. En ausencias largas o repetidas, confirma tu caso con la empresa y la aseguradora."], callout:{title:"Por qué importa",text:"La primera pregunta práctica es quién te paga durante la ausencia. Para muchos empleados, la empresa cubre el periodo inicial; después puede ser relevante el Krankengeld del seguro público si se cumplen sus condiciones.",tone:"success"} },
      { heading:"Baja por teléfono y videoconsulta en 2026", paragraphs:["La certificación telefónica para determinadas enfermedades leves sigue existiendo a 8 de octubre de 2026. El Gobierno federal ha anunciado la intención de eliminarla, pero su información actual indica que las reglas vigentes continúan hasta que el cambio se implemente.","Un anuncio político no es lo mismo que una norma ya en vigor. Como este punto está cambiando, comprueba la información federal o pregunta a tu consulta antes de depender de esta vía."], resources: englishGuide.sickLeave.sections[4].resources },
      { heading:"Checklist sencillo para un día de baja", paragraphs:["Para un empleado normal, una secuencia útil es: avisar a la empresa, comprobar si exige justificante desde el primer día, contactar con una consulta cuando sea necesario, guardar las fechas certificadas y volver a informar si cambia la fecha prevista de regreso.","Si estás en el extranjero, tienes seguro privado, trabajas como Minijob en un hogar o se trata de un accidente laboral, no des por hecho que el flujo estándar de la eAU se aplica igual."], bullets:["Avisar a la empresa.","Comprobar el plazo del justificante.","Obtener la determinación médica cuando proceda.","Guardar tus propias fechas.","Comunicar las prórrogas rápidamente."] }
    ],
    faqs:[
      {question:"¿Tengo que avisar a mi empresa si el médico envía una eAU?",answer:"Sí. La eAU cambia cómo llegan los datos médicos a la empresa, pero no elimina tu obligación de comunicar la incapacidad y su duración prevista."},
      {question:"¿Siempre tengo tres días antes de necesitar justificante?",answer:"No. La regla legal actual se activa cuando la incapacidad dura más de tres días naturales, pero la empresa puede exigir confirmación antes, incluso desde el primer día."},
      {question:"¿Ya es obligatorio el justificante desde el primer día para todo el mundo en octubre de 2026?",answer:"No. Se ha anunciado un endurecimiento, pero el Gobierno federal indica que las reglas actuales siguen vigentes hasta su implementación."},
      {question:"¿Todavía existe la baja médica por teléfono en Alemania?",answer:"Sí, en los casos que cumplen los requisitos, a 8 de octubre de 2026. Se ha anunciado su posible eliminación, así que conviene volver a comprobarlo más adelante."}
    ],
    sources: englishGuide.sickLeave.sources.map((s)=>({...s,note:s.note}))
  },
  doctor: {
    ...englishGuide.doctor,
    slug: practicalGuideSlugs.doctor.es,
    title:"Cómo encontrar médico en Alemania: Hausarzt, 116117 y urgencias",
    description:"Guía práctica para encontrar Hausarzt o especialista en Alemania, usar el 116117, entender cuándo puede hacer falta un código de derivación y distinguir entre consulta normal, 116117 y 112.",
    eyebrow:"Guía práctica de salud",
    summary:"El sistema sanitario alemán se entiende mejor si separas tres necesidades: un médico habitual para la atención normal, el servicio 116117 para búsqueda de consultas, citas y atención urgente fuera de horario, y el 112 para emergencias vitales.",
    takeaways:["El Hausarzt suele ser el mejor primer contacto para problemas médicos cotidianos y seguimiento.","El servicio oficial 116117 permite buscar médicos y, para asegurados públicos, ofrece servicio de citas.","Para citas de Hausarzt mediante 116117 no necesitas derivación ni Vermittlungscode.","116117 sirve para atención urgente no vital fuera del horario habitual; 112 es para emergencias vitales.","La búsqueda de 116117 permite filtrar por especialidad y criterios adicionales como idiomas."],
    sections:[
      {heading:"Empieza por encontrar un Hausarzt",paragraphs:["Un Hausarzt es un médico de cabecera y suele ser el mejor primer punto de contacto para enfermedades habituales, problemas recurrentes, vacunas, revisiones básicas y derivaciones a especialistas.","Alemania no asigna automáticamente un médico de cabecera fijo a cada recién llegado. Normalmente debes buscar una consulta y preguntar si acepta nuevos pacientes. La disponibilidad cambia mucho según la ciudad, así que conviene tener más de una opción cerca antes de necesitarla."],bullets:["Busca cerca de casa, universidad o trabajo.","Comprueba si la consulta acepta tu tipo de seguro.","Pregunta si acepta nuevos pacientes.","Guarda horarios y sistema de citas."]},
      {heading:"Usa la búsqueda oficial de médicos de 116117",paragraphs:["El servicio 116117 forma parte del sistema de asistencia médica concertada. Su buscador de médicos y psicoterapeutas permite encontrar consultas por zona y filtrar por especialidad y otros criterios.","Es especialmente útil cuando una búsqueda genérica muestra muchas consultas pero no deja claro cuáles participan en la asistencia ambulatoria del seguro público. También puedes usar filtros relacionados con idiomas."],resources:englishGuide.doctor.sections[1].resources},
      {heading:"Cuándo ayuda el servicio de citas 116117",paragraphs:["Las personas con seguro público pueden usar 116117 para reservar determinadas citas por internet o teléfono. Las reglas dependen del tipo de médico.","Según la KBV, no necesitas derivación ni Vermittlungscode para citas con Hausarzt, oftalmólogo, ginecólogo o pediatra, ni para una primera consulta psicoterapéutica. Para muchos otros especialistas sí puede ser necesario un código cuando utilizas esta vía formal de citas.","Que el servicio 116117 exija código en determinados casos no significa que nunca puedas contactar directamente con esa consulta especialista."],resources:englishGuide.doctor.sections[2].resources},
      {heading:"Diferencia entre 116117 y 112",paragraphs:["116117 es el servicio médico de guardia para problemas que normalmente trataría una consulta pero que no pueden esperar razonablemente hasta el siguiente horario habitual. Funciona en toda Alemania sin prefijo.","112 es el número de emergencias para situaciones que ponen en peligro la vida. Dificultad respiratoria grave, pérdida de consciencia o hemorragias importantes corresponden a emergencias, no a un servicio de citas.","Si no sabes si un problema no vital puede esperar, el navegador de pacientes de 116117 puede orientarte hacia el nivel adecuado de atención. No sustituye un diagnóstico."],callout:{title:"Regla sencilla",text:"Problema normal que puede esperar: consulta habitual. Problema urgente con consultas cerradas: 116117. Emergencia vital: 112.",tone:"warning"},resources:englishGuide.doctor.sections[3].resources},
      {heading:"Qué preparar antes de la cita",paragraphs:["Lleva la tarjeta del seguro o los datos de cobertura, una lista de medicamentos y documentos relevantes si el problema ya se ha estudiado anteriormente. Si el idioma te preocupa, pregunta antes qué idiomas ofrece la consulta.","Para una enfermedad crónica, intenta mantener el mismo Hausarzt cuando encuentres una consulta adecuada. Un médico que conoce tu historial puede coordinar mejor derivaciones y seguimiento."],bullets:["Tarjeta o datos del seguro.","Lista de medicamentos y alergias.","Informes o resultados relevantes.","Una lista breve de preguntas."]},
      {heading:"Plan práctico para recién llegados",paragraphs:["No esperes a estar enfermo para aprender el sistema. Cuando tu cobertura esté activa, localiza dos consultas de Hausarzt cercanas, guarda 116117 y 112 en el móvil y comprueba cómo gestiona tu aseguradora la atención rutinaria.","Con esa preparación tienes una ruta clara para atención normal, urgencias fuera de horario y emergencias reales."]}
    ],
    faqs:[
      {question:"¿Necesito derivación para ir al Hausarzt?",answer:"No. El Hausarzt es atención primaria y el servicio de citas 116117 tampoco exige derivación ni Vermittlungscode para citas de Hausarzt."},
      {question:"¿Puede 116117 ayudarme a encontrar un médico que hable inglés?",answer:"El buscador oficial incluye filtros adicionales y los datos de las consultas pueden indicar idiomas. La disponibilidad depende de cada zona."},
      {question:"¿116117 es un número de emergencias?",answer:"Es para atención urgente no vital y servicios de orientación/citas. En una emergencia que pone en peligro la vida, llama al 112."},
      {question:"¿Pueden usar 116117 las personas con seguro privado?",answer:"El servicio médico de guardia está disponible independientemente de tener seguro público o privado; la vía formal de citas descrita por 116117 está orientada principalmente a personas con seguro público."}
    ],
    sources: englishGuide.doctor.sources
  },
  payslip: {
    ...englishGuide.payslip,
    slug: practicalGuideSlugs.payslip.es,
    title:"Nómina alemana explicada: Brutto, Netto, impuestos y deducciones",
    description:"Cómo leer una Lohnabrechnung o Gehaltsabrechnung alemana, qué debe mostrar la empresa, qué significan los impuestos y cotizaciones habituales y por qué tu neto puede cambiar de un mes a otro.",
    eyebrow:"Guía práctica de salario",
    summary:"Una nómina alemana se entiende mejor si la divides en cuatro capas: salario bruto, información fiscal, cotizaciones sociales y pago final. El diseño cambia según el proveedor de nóminas, pero la liquidación debe identificar el periodo y la composición de la remuneración.",
    takeaways:["El §108 de la Gewerbeordnung exige una liquidación de remuneración en formato de texto cuando se paga el salario, salvo cuando la información relevante no ha cambiado desde la última liquidación correcta.","La liquidación debe identificar el periodo y la composición del salario, incluidos complementos, asignaciones y deducciones relevantes.","Brutto no es la cantidad que llega al banco; Netto se obtiene después de impuestos de nómina y cotizaciones aplicables.","La Lohnsteuer se calcula mediante el sistema de nómina utilizando reglas anualizadas y las características fiscales electrónicas del trabajador.","Una prima, ausencia sin sueldo, cambio fiscal o pago extraordinario puede hacer variar el neto de un mes a otro."],
    sections:[
      {heading:"Los cuatro bloques de una nómina alemana",paragraphs:["El diseño cambia según el software, pero casi siempre puedes entender la nómina localizando cuatro bloques: tus datos, la remuneración bruta, las deducciones y el importe final transferido.","No empieces intentando descifrar todas las abreviaturas. Primero confirma que el periodo, el bruto y el importe final coinciden con lo esperado; después revisa las líneas que explican la diferencia."],bullets:["Periodo y datos del trabajador.","Salario bruto y primas o complementos.","Impuestos y cotizaciones sociales.","Neto e importe realmente pagado."]},
      {heading:"Qué debe proporcionar la empresa",paragraphs:["El §108 GewO exige una liquidación de remuneración en formato de texto al pagarse el salario. Debe mostrar al menos el periodo de liquidación y la composición de la remuneración.","La ley menciona expresamente el tipo y cuantía de complementos, asignaciones y otras remuneraciones, así como deducciones, anticipos y pagos a cuenta. Si la información relevante no ha cambiado desde la última liquidación correcta, puede no ser necesaria una nueva."],resources:englishGuide.payslip.sections[1].resources},
      {heading:"Brutto: qué aparece antes de las deducciones",paragraphs:["El salario base contractual suele iniciar el cálculo. Dependiendo del trabajo, el bruto también puede incluir horas extra, turnos, bonus, comisiones, pagas adicionales, beneficios o correcciones de otro periodo.","Un bruto mayor no siempre produce un aumento proporcional del neto, porque el impuesto sobre salarios se calcula con reglas anualizadas y algunas cotizaciones tienen límites."],callout:{title:"Comprobación útil",text:"Si el bruto es incorrecto, investiga eso primero. El cálculo fiscal puede ser perfecto y aun así dar un pago final incorrecto si las horas, el bonus o el salario de entrada están mal.",tone:"note"}},
      {heading:"Lohnsteuer, Kirchensteuer y Solidaritätszuschlag",paragraphs:["La Lohnsteuer es el impuesto sobre salarios retenido por la empresa. El Ministerio Federal de Finanzas explica que el salario corriente se convierte a una cifra anual para el cálculo y que se tienen en cuenta características electrónicas como la clase fiscal y determinadas deducciones.","Kirchensteuer solo aparece cuando el trabajador está sujeto al impuesto eclesiástico. El Solidaritätszuschlag no es una deducción fija que pague necesariamente todo empleado; depende del cálculo aplicable.","Si cambias de clase fiscal u otra característica electrónica, el efecto puede aparecer en una nómina posterior cuando la empresa reciba los datos actualizados."],resources:englishGuide.payslip.sections[3].resources},
      {heading:"Las abreviaturas de las cotizaciones sociales",paragraphs:["Para empleados sujetos a la seguridad social alemana, las familias habituales son seguro médico (KV), pensiones (RV), desempleo (AV) y dependencia (PV). El importe exacto depende del tipo de empleo y de las bases y límites aplicables.","Por eso un Minijob, Midijob, Werkstudent o empleo normal pueden tener patrones de deducción muy distintos incluso con salarios brutos similares."],bullets:["KV — Krankenversicherung (seguro médico).","RV — Rentenversicherung (pensiones).","AV — Arbeitslosenversicherung (desempleo).","PV — Pflegeversicherung (dependencia)."]},
      {heading:"Por qué el importe pagado puede diferir del Netto",paragraphs:["Muchas nóminas distinguen entre el neto calculado y el importe final transferido. Reembolsos, beneficios, anticipos, embargos u otros ajustes pueden aparecer entre ambos.","Si la transferencia bancaria no coincide con el primer neto que ves, busca una línea Auszahlungsbetrag o equivalente antes de asumir que la nómina es incorrecta."]},
      {heading:"Comprobación de cinco minutos",paragraphs:["Revisa el periodo, bruto contractual, variables, datos fiscales, situación de seguro y pago final. Compara los cambios raros con el mes anterior en lugar de intentar descifrar todos los códigos de golpe.","Si algo sigue sin cuadrar, pregunta a nóminas o RR. HH. qué dato cambió. Para problemas fiscales puede corresponder Finanzamt o un profesional; para el estado de seguro, la aseguradora."],bullets:["¿El bruto es correcto?","¿Horas extra, primas y ausencias están reflejadas?","¿La clase fiscal parece correcta?","¿Las cotizaciones encajan con tu tipo de empleo?","¿El pago final coincide con tu banco?"]}
    ],
    faqs:[
      {question:"¿La empresa tiene que darme una nómina todos los meses?",answer:"La ley exige una liquidación en formato de texto al pagarse el salario, pero la obligación puede desaparecer si la información relevante no ha cambiado desde la última liquidación correcta."},
      {question:"¿Por qué mi salario neto cambia este mes?",answer:"Entre las causas habituales están primas, horas extra, ausencias sin sueldo, cambios fiscales, correcciones de nómina u otros pagos extraordinarios."},
      {question:"¿Qué diferencia hay entre Netto y Auszahlungsbetrag?",answer:"Netto es el resultado después de las principales deducciones de nómina. El pago final puede ajustarse por otros conceptos y mostrarse aparte como Auszahlungsbetrag."},
      {question:"¿Puedo calcular el neto alemán con un porcentaje fijo?",answer:"No de forma fiable. La Lohnsteuer usa reglas anualizadas y características personales, mientras que las cotizaciones dependen del tipo de empleo y límites aplicables."}
    ],
    sources: englishGuide.payslip.sources
  }
};

const de: Record<PracticalGuideKey, Guide> = {
  sickLeave: {
    ...englishGuide.sickLeave,
    slug: practicalGuideSlugs.sickLeave.de,
    title:"Krankschreibung in Deutschland 2026: eAU, Fristen und Entgeltfortzahlung",
    description:"Wie Krankmeldung und elektronische Arbeitsunfähigkeitsbescheinigung 2026 funktionieren, wann der Arbeitgeber informiert werden muss und was die Sechs-Wochen-Regel bedeutet.",
    eyebrow:"Praxisratgeber Arbeit",
    summary:"Wer krankheitsbedingt nicht arbeiten kann, hat zwei getrennte Pflichten: den Arbeitgeber unverzüglich informieren und eine ärztliche Feststellung einholen, wenn sie erforderlich ist. Für die meisten gesetzlich Versicherten läuft der Nachweis über die eAU statt über eine Papierbescheinigung.",
    takeaways:["Die Arbeitsunfähigkeit und ihre voraussichtliche Dauer müssen dem Arbeitgeber unverzüglich mitgeteilt werden.","Nach der derzeitigen gesetzlichen Grundregel ist eine ärztliche Feststellung nötig, wenn die Arbeitsunfähigkeit länger als drei Kalendertage dauert; der Arbeitgeber kann sie früher verlangen.","Bei den meisten gesetzlich Versicherten übermittelt die Praxis die eAU an die Krankenkasse und der Arbeitgeber ruft die Daten elektronisch ab.","Die Entgeltfortzahlung durch den Arbeitgeber kann bei erfüllten Voraussetzungen grundsätzlich bis zu sechs Wochen dauern.","Am 8. Oktober 2026 hat die angekündigte politische Verschärfung die geltende Regel noch nicht ersetzt."],
    sections:[
      {heading:"Schritt 1: zuerst den Arbeitgeber informieren",paragraphs:["Die Krankschreibung ersetzt nicht die Krankmeldung beim Arbeitgeber. §5 EntgFG verlangt, die Arbeitsunfähigkeit und ihre voraussichtliche Dauer unverzüglich mitzuteilen. Nutze den im Betrieb vorgesehenen Kanal: Vorgesetzte, HR-System, Telefon, App oder E-Mail.","Warte mit der Meldung nicht auf den Arzttermin. Der Arbeitgeber muss wissen, dass du nicht arbeitest, auch wenn die medizinische Bestätigung später elektronisch folgt."],bullets:["Melde die Abwesenheit, sobald klar ist, dass du nicht arbeiten kannst.","Nenne die voraussichtliche Dauer, wenn bekannt.","Beachte strengere interne Regeln in Vertrag oder Betriebsregelung."],callout:{title:"Stand Oktober 2026",text:"Die Bundesregierung hat strengere Nachweispflichten angekündigt. Laut ihrer eigenen Information gelten die bisherigen Regeln aber weiter, bis die Änderungen tatsächlich umgesetzt sind.",tone:"note"}},
      {heading:"Schritt 2: wann eine ärztliche Feststellung nötig ist",paragraphs:["Nach der aktuellen gesetzlichen Grundregel muss bei einer Arbeitsunfähigkeit von mehr als drei Kalendertagen spätestens am nächsten Arbeitstag eine ärztliche Feststellung vorliegen. Der Arbeitgeber darf sie früher, auch ab dem ersten Tag, verlangen.","Deshalb können Beschäftigte bei unterschiedlichen Arbeitgebern praktisch verschiedene Fristen haben. Prüfe Arbeitsvertrag, Tarifvertrag und betriebliche Regelung."],bullets:["Gesetzliche Grundregel: mehr als drei Kalendertage.","Der Arbeitgeber kann einen früheren Nachweis verlangen.","Bei längerer Erkrankung ist eine Folgefeststellung erforderlich."]},
      {heading:"So funktioniert die eAU bei gesetzlicher Krankenversicherung",paragraphs:["Für gesetzlich versicherte Beschäftigte wurde die Papierübergabe weitgehend durch die elektronische Arbeitsunfähigkeitsbescheinigung (eAU) ersetzt. Die Praxis übermittelt die Daten an die Krankenkasse; der Arbeitgeber ruft die relevanten Informationen elektronisch ab.","Die eAU ersetzt die Papierübergabe, nicht die Krankmeldung beim Arbeitgeber. Bewahre deine eigenen Unterlagen und Daten auf.","In Ausnahmen, etwa bei bestimmten privat Versicherten oder Behandlungen außerhalb der vertragsärztlichen Versorgung, können andere Abläufe gelten."],resources:englishGuide.sickLeave.sections[2].resources},
      {heading:"Was die Sechs-Wochen-Regel wirklich bedeutet",paragraphs:["§3 EntgFG sieht bei erfüllten Voraussetzungen eine Entgeltfortzahlung durch den Arbeitgeber von bis zu sechs Wochen vor, wenn die Arbeitsunfähigkeit krankheitsbedingt und ohne eigenes Verschulden eintritt.","'Sechs Wochen' bedeutet nicht automatisch sechs neue Wochen bei jeder erneuten Abwesenheit. Wiederholte Arbeitsunfähigkeit wegen derselben Krankheit und besondere Beschäftigungssituationen können die Berechnung verändern."],callout:{title:"Warum das wichtig ist",text:"Praktisch geht es zuerst darum, wer während der Abwesenheit zahlt. Nach der Arbeitgeberphase kann bei gesetzlich Versicherten Krankengeld relevant werden, wenn die Voraussetzungen erfüllt sind.",tone:"success"}},
      {heading:"Telefonische und Video-Krankschreibung 2026",paragraphs:["Die telefonische Krankschreibung bei bestimmten leichten Erkrankungen besteht am 8. Oktober 2026 weiterhin. Die Bundesregierung hat ihre Abschaffung angekündigt, erklärt aber zugleich, dass die bestehenden Regeln bis zur Umsetzung gelten.","Eine politische Ankündigung ist noch keine geltende Rechtsänderung. Prüfe den aktuellen Stand bei der Bundesregierung oder deiner Praxis, wenn diese Möglichkeit für dich wichtig ist."],resources:englishGuide.sickLeave.sections[4].resources},
      {heading:"Einfache Checkliste für einen Krankheitstag",paragraphs:["Eine sinnvolle Reihenfolge ist: Arbeitgeber informieren, Nachweisfrist prüfen, bei Bedarf die ärztliche Feststellung einholen, die bescheinigten Daten selbst dokumentieren und Verlängerungen erneut melden.","Bei Auslandsaufenthalt, privater Versicherung, Haushalts-Minijob oder Arbeitsunfall kann der Standardablauf abweichen."],bullets:["Arbeitgeber informieren.","Nachweisfrist prüfen.","Ärztliche Feststellung einholen, wenn nötig.","Eigene Daten aufbewahren.","Verlängerungen schnell melden."]}
    ],
    faqs:[
      {question:"Muss ich den Arbeitgeber trotz eAU selbst informieren?",answer:"Ja. Die eAU verändert die Übermittlung der medizinischen Daten, nicht die Pflicht, die Arbeitsunfähigkeit und ihre voraussichtliche Dauer mitzuteilen."},
      {question:"Habe ich immer drei Tage Zeit ohne Nachweis?",answer:"Nein. Die gesetzliche Grundregel knüpft an mehr als drei Kalendertage an, aber der Arbeitgeber kann einen Nachweis früher verlangen, auch ab Tag eins."},
      {question:"Ist seit Oktober 2026 für alle ein Nachweis ab dem ersten Tag Pflicht?",answer:"Nein. Eine Verschärfung wurde angekündigt, aber laut Bundesregierung gelten die bisherigen Regeln bis zur Umsetzung weiter."},
      {question:"Gibt es die telefonische Krankschreibung noch?",answer:"Ja, in den dafür vorgesehenen Fällen am 8. Oktober 2026. Da Änderungen angekündigt sind, sollte der Status später erneut geprüft werden."}
    ],
    sources:englishGuide.sickLeave.sources
  },
  doctor:{
    ...englishGuide.doctor,
    slug:practicalGuideSlugs.doctor.de,
    title:"Arzt finden in Deutschland: Hausarzt, 116117 und Bereitschaftsdienst",
    description:"Praxisratgeber zur Hausarzt- und Facharztsuche, zum 116117-Terminservice, zu Vermittlungscodes und zur Abgrenzung zwischen Praxis, 116117 und 112.",
    eyebrow:"Praxisratgeber Gesundheit",
    summary:"Das deutsche Gesundheitssystem wird übersichtlicher, wenn du drei Wege trennst: Hausarzt für normale Versorgung, 116117 für Arztsuche, Termine und dringende Versorgung außerhalb der Sprechzeiten, und 112 für lebensbedrohliche Notfälle.",
    takeaways:["Ein Hausarzt ist meist der sinnvollste erste Ansprechpartner für alltägliche Beschwerden und kontinuierliche Betreuung.","Der offizielle Dienst 116117 bietet Arztsuche und für gesetzlich Versicherte einen Terminservice.","Für Hausarzttermine über 116117 sind keine Überweisung und kein Vermittlungscode nötig.","116117 ist für dringende, aber nicht lebensbedrohliche Probleme außerhalb regulärer Praxiszeiten; 112 für lebensbedrohliche Notfälle.","Die 116117-Suche kann nach Fachgebiet und Zusatzmerkmalen wie Sprachen filtern."],
    sections:[
      {heading:"Zuerst einen Hausarzt finden",paragraphs:["Der Hausarzt ist für viele alltägliche Erkrankungen, wiederkehrende Beschwerden, Impfungen, Basisuntersuchungen und Überweisungen die beste erste Anlaufstelle.","Neuzugezogene bekommen in Deutschland nicht automatisch einen festen Hausarzt. Du suchst selbst eine Praxis und fragst, ob neue Patienten aufgenommen werden. Je nach Stadt kann die Verfügbarkeit stark variieren."],bullets:["In der Nähe von Wohnung, Uni oder Arbeit suchen.","Prüfen, ob die Praxis deine Versicherungsart akzeptiert.","Nachfragen, ob neue Patienten aufgenommen werden.","Öffnungszeiten und Buchungsweg speichern."]},
      {heading:"Die offizielle 116117-Arztsuche nutzen",paragraphs:["Der Patientenservice 116117 gehört zur vertragsärztlichen Versorgung. Über die Arzt- und Psychotherapeutensuche kannst du Praxen in deiner Nähe finden und nach Fachgebiet und weiteren Kriterien filtern.","Das hilft besonders, wenn allgemeine Kartendienste viele Treffer zeigen, aber nicht deutlich machen, welche Praxen an der gesetzlichen ambulanten Versorgung teilnehmen. Auch Fremdsprachen können als Merkmal hinterlegt sein."],resources:englishGuide.doctor.sections[1].resources},
      {heading:"Wann der 116117-Terminservice hilft",paragraphs:["Gesetzlich Versicherte können über 116117 bestimmte Termine online oder telefonisch buchen. Welche Voraussetzungen gelten, hängt von der Arztgruppe ab.","Laut KBV braucht man für Hausarzt, Augenarzt, Frauenarzt, Kinderarzt und die psychotherapeutische Sprechstunde keine Überweisung und keinen Vermittlungscode. Für viele andere Facharzttermine kann beim Terminservice ein Code erforderlich sein.","Die Code-Pflicht im Terminservice bedeutet nicht, dass man eine Facharztpraxis niemals direkt kontaktieren darf."],resources:englishGuide.doctor.sections[2].resources},
      {heading:"116117 und 112 auseinanderhalten",paragraphs:["116117 ist der ärztliche Bereitschaftsdienst für Beschwerden, die normalerweise in einer Praxis behandelt würden, aber nicht bis zur nächsten regulären Sprechzeit warten können.","112 ist die Notrufnummer bei Lebensgefahr. Starke Atemnot, Bewusstlosigkeit oder schwere unkontrollierte Blutungen gehören zum Rettungsdienst, nicht zum Terminservice.","Wenn du unsicher bist, ob ein nicht lebensbedrohliches Problem warten kann, kann der Patienten-Navi von 116117 zur passenden Versorgungsebene führen. Er stellt keine Diagnose."],callout:{title:"Einfache Regel",text:"Normales Problem, das warten kann: Praxis. Dringend bei geschlossenen Praxen: 116117. Lebensbedrohlicher Notfall: 112.",tone:"warning"},resources:englishGuide.doctor.sections[3].resources},
      {heading:"Was du zum Termin mitbringen solltest",paragraphs:["Nimm die Gesundheitskarte oder Versicherungsdaten, eine Medikamentenliste und relevante Vorbefunde mit. Wenn Sprache ein Thema ist, frage vorher nach verfügbaren Sprachen.","Bei chronischen Problemen ist ein fester Hausarzt sinnvoll, sobald du eine passende Praxis gefunden hast. Eine Praxis mit deiner Vorgeschichte kann Überweisungen und Kontrollen besser koordinieren."],bullets:["Gesundheitskarte/Versicherungsdaten.","Medikamenten- und Allergieliste.","Relevante Briefe oder Befunde.","Kurze Liste deiner Fragen."]},
      {heading:"Ein praktischer Plan für Neuzugezogene",paragraphs:["Warte nicht bis zur Krankheit. Sobald der Versicherungsschutz aktiv ist, suche zwei nahe Hausarztpraxen, speichere 116117 und 112 im Handy und prüfe die normalen Leistungen deiner Krankenkasse.","Damit hast du klare Wege für normale Versorgung, dringende Probleme außerhalb der Sprechzeiten und echte Notfälle."]}
    ],
    faqs:[
      {question:"Brauche ich eine Überweisung zum Hausarzt?",answer:"Nein. Der Hausarzt ist Primärversorgung, und auch der 116117-Terminservice verlangt für Hausarzttermine keine Überweisung und keinen Vermittlungscode."},
      {question:"Kann 116117 einen englischsprachigen Arzt finden?",answer:"Die offizielle Arztsuche enthält Zusatzfilter; Praxisdaten können Fremdsprachen ausweisen. Die tatsächliche Verfügbarkeit hängt vom Ort ab."},
      {question:"Ist 116117 eine Notrufnummer?",answer:"116117 ist für dringende, nicht lebensbedrohliche Versorgung sowie Navigation und Termine. Bei Lebensgefahr gilt 112."},
      {question:"Können privat Versicherte 116117 nutzen?",answer:"Der ärztliche Bereitschaftsdienst steht unabhängig von gesetzlicher oder privater Versicherung zur Verfügung; der formale Terminservice ist vor allem auf gesetzlich Versicherte ausgerichtet."}
    ],
    sources:englishGuide.doctor.sources
  },
  payslip:{
    ...englishGuide.payslip,
    slug:practicalGuideSlugs.payslip.de,
    title:"Gehaltsabrechnung erklärt: Brutto, Netto, Steuern und Abzüge",
    description:"So liest du eine deutsche Lohn- oder Gehaltsabrechnung, was der Arbeitgeber ausweisen muss, was typische Steuer- und Sozialabgaben bedeuten und warum sich das Netto ändern kann.",
    eyebrow:"Praxisratgeber Gehalt",
    summary:"Eine deutsche Gehaltsabrechnung wird verständlicher, wenn du vier Ebenen trennst: Bruttovergütung, steuerliche Angaben, Sozialabgaben und den endgültigen Auszahlungsbetrag. Das Layout variiert, aber die Abrechnung muss Zeitraum und Zusammensetzung der Vergütung erkennen lassen.",
    takeaways:["§108 GewO verlangt bei Zahlung des Arbeitsentgelts grundsätzlich eine Abrechnung in Textform; bei unveränderten Angaben kann eine neue Abrechnung entfallen.","Die Abrechnung muss Abrechnungszeitraum und Zusammensetzung des Entgelts einschließlich relevanter Zuschläge, Zulagen und Abzüge erkennen lassen.","Brutto ist nicht der Bankbetrag; Netto entsteht nach Lohnsteuer und anwendbaren Arbeitnehmerbeiträgen.","Die Lohnsteuer wird nach annualisierten Regeln und den elektronischen Lohnsteuermerkmalen berechnet.","Bonus, unbezahlte Abwesenheit, geänderte Steuerdaten oder Einmalzahlungen können das Monatsnetto verändern."],
    sections:[
      {heading:"Vier Blöcke auf jeder Gehaltsabrechnung",paragraphs:["Layouts unterscheiden sich, aber meist lassen sich vier Bereiche erkennen: persönliche/abrechnungsbezogene Daten, Bruttovergütung, Abzüge und der endgültige Zahlbetrag.","Beginne nicht mit jeder Abkürzung. Prüfe zuerst Zeitraum, Brutto und Auszahlungsbetrag. Danach lassen sich die Zeilen dazwischen gezielt nachvollziehen."],bullets:["Abrechnungszeitraum und Personaldaten.","Bruttogehalt und variable Bestandteile.","Steuern und Sozialabgaben.","Netto und tatsächlicher Auszahlungsbetrag."]},
      {heading:"Was der Arbeitgeber ausweisen muss",paragraphs:["§108 GewO verlangt bei Zahlung des Arbeitsentgelts eine Abrechnung in Textform. Mindestens Abrechnungszeitraum und Zusammensetzung des Entgelts müssen erkennbar sein.","Genannt werden insbesondere Art und Höhe von Zuschlägen, Zulagen und sonstigen Vergütungen sowie Art und Höhe von Abzügen, Abschlags- und Vorschusszahlungen. Bei unveränderten Angaben kann eine erneute Abrechnung entfallen."],resources:englishGuide.payslip.sections[1].resources},
      {heading:"Brutto: was vor den Abzügen steht",paragraphs:["Ausgangspunkt ist normalerweise das vertragliche Grundgehalt. Je nach Job können Überstunden, Schichtzuschläge, Boni, Provisionen, Sonderzahlungen, Sachbezüge oder Korrekturen hinzukommen.","Mehr Brutto führt nicht immer proportional zu mehr Netto, weil die Lohnsteuer annualisiert berechnet wird und Sozialabgaben teilweise Grenzen haben."],callout:{title:"Nützlicher Check",text:"Ist das Brutto falsch, prüfe zuerst Stunden, Bonus oder Grundgehalt. Eine korrekt berechnete Steuer kann trotzdem zu einem falschen Zahlbetrag führen, wenn der Ausgangswert nicht stimmt.",tone:"note"}},
      {heading:"Lohnsteuer, Kirchensteuer und Solidaritätszuschlag",paragraphs:["Lohnsteuer wird vom Arbeitgeber einbehalten. Das Bundesfinanzministerium erläutert, dass laufender Arbeitslohn für die Berechnung auf einen Jahresarbeitslohn hochgerechnet wird und elektronische Merkmale wie Steuerklasse und Freibeträge einfließen.","Kirchensteuer erscheint nur bei Kirchensteuerpflicht. Der Solidaritätszuschlag ist keine pauschale Abgabe für jeden Beschäftigten, sondern hängt von der konkreten Berechnung ab.","Ändert sich die Steuerklasse oder ein anderes elektronisches Merkmal, kann der Effekt erst in einer späteren Abrechnung sichtbar werden."],resources:englishGuide.payslip.sections[3].resources},
      {heading:"Die Abkürzungen der Sozialversicherung",paragraphs:["Bei sozialversicherungspflichtigen Beschäftigten tauchen häufig Krankenversicherung (KV), Rentenversicherung (RV), Arbeitslosenversicherung (AV) und Pflegeversicherung (PV) auf. Der genaue Arbeitnehmeranteil hängt von Beschäftigungsart und Bemessungsgrundlagen ab.","Minijob, Midijob, Werkstudent und reguläre Beschäftigung können deshalb selbst bei ähnlichem Brutto sehr unterschiedliche Abzugsmuster haben."],bullets:["KV — Krankenversicherung.","RV — Rentenversicherung.","AV — Arbeitslosenversicherung.","PV — Pflegeversicherung."]},
      {heading:"Warum Auszahlungsbetrag und Netto abweichen können",paragraphs:["Viele Abrechnungen unterscheiden zwischen berechnetem Netto und tatsächlich überwiesenem Betrag. Erstattungen, Sachbezüge, Vorschüsse, Pfändungen oder andere Verrechnungsposten können dazwischenliegen.","Wenn die Überweisung nicht dem ersten Netto-Wert entspricht, suche nach Auszahlungsbetrag oder einer ähnlichen Schlusszeile."]},
      {heading:"Fünf-Minuten-Check der Abrechnung",paragraphs:["Prüfe Zeitraum, vertragliches Brutto, variable Bestandteile, Steuermerkmale, Versicherungsstatus und Auszahlung. Vergleiche auffällige Änderungen mit dem Vormonat, statt jeden Code isoliert zu entschlüsseln.","Bleibt etwas unklar, frage Payroll oder HR, welcher Eingabewert sich geändert hat. Bei Steuerfragen kann das Finanzamt oder professionelle Steuerberatung zuständig sein; beim Versicherungsstatus die Krankenkasse."],bullets:["Stimmt das Brutto?","Sind Überstunden, Boni und Fehlzeiten korrekt?","Ist die Steuerklasse plausibel?","Passen die Versicherungsabzüge zur Beschäftigungsart?","Stimmt die Auszahlung mit dem Konto überein?"]}
    ],
    faqs:[
      {question:"Muss ich jeden Monat eine Gehaltsabrechnung bekommen?",answer:"Grundsätzlich ist bei der Entgeltzahlung eine Abrechnung in Textform vorgesehen; bei unveränderten relevanten Angaben kann eine neue Abrechnung jedoch entfallen."},
      {question:"Warum ist mein Netto diesen Monat anders?",answer:"Häufige Gründe sind Boni, Überstunden, unbezahlte Abwesenheit, geänderte Steuermerkmale, Korrekturen oder Einmalzahlungen."},
      {question:"Was ist der Unterschied zwischen Netto und Auszahlungsbetrag?",answer:"Netto ist das Ergebnis nach den wesentlichen Abzügen. Weitere Verrechnungsposten können den endgültigen Auszahlungsbetrag verändern."},
      {question:"Kann man deutsches Netto mit einem festen Prozentsatz berechnen?",answer:"Nicht zuverlässig. Lohnsteuer nutzt annualisierte Regeln und persönliche Merkmale; Sozialabgaben hängen von Beschäftigungsart und Grenzen ab."}
    ],
    sources:englishGuide.payslip.sources
  }
};

const fr: Record<PracticalGuideKey, Guide> = {
  sickLeave:{
    ...englishGuide.sickLeave,
    slug:practicalGuideSlugs.sickLeave.fr,
    title:"Arrêt maladie en Allemagne en 2026 : eAU, délais et maintien du salaire",
    description:"Comment fonctionnent la Krankmeldung et l'arrêt maladie électronique en Allemagne en 2026, quand prévenir l'employeur, quand un certificat est requis et ce que signifie la règle des six semaines.",
    eyebrow:"Guide pratique du travail",
    summary:"Si vous êtes trop malade pour travailler en Allemagne, deux obligations sont distinctes : prévenir rapidement l'employeur et obtenir une constatation médicale lorsqu'elle est requise. Pour la plupart des salariés assurés dans le public, le justificatif passe désormais par le système eAU plutôt que par un document papier remis à l'employeur.",
    takeaways:["Vous devez informer sans délai l'employeur de l'incapacité de travail et de sa durée prévisible.","Selon la règle actuellement en vigueur, une constatation médicale est normalement nécessaire lorsque l'incapacité dure plus de trois jours calendaires, mais l'employeur peut l'exiger plus tôt.","Pour la plupart des salariés assurés dans le public, le cabinet transmet l'eAU à la caisse et l'employeur récupère les données électroniquement.","Le maintien du salaire par l'employeur peut en principe durer jusqu'à six semaines lorsque les conditions légales sont remplies.","Au 8 octobre 2026, le projet politique imposant un certificat dès le premier jour n'a pas encore remplacé la règle actuelle."],
    sections:[
      {heading:"Étape 1 : prévenir d'abord l'employeur",paragraphs:["L'arrêt maladie ne remplace pas l'obligation de signaler l'absence. Le §5 EntgFG impose d'informer sans délai l'employeur de l'incapacité et de sa durée prévisible. Utilisez le canal prévu par l'entreprise : responsable, RH, téléphone, application ou e-mail.","N'attendez pas le rendez-vous médical pour signaler votre absence. L'employeur doit savoir que vous ne travaillerez pas, même si la confirmation médicale arrive ensuite par voie électronique."],bullets:["Signalez l'absence dès que vous savez que vous ne pouvez pas travailler.","Indiquez la durée prévisible si vous la connaissez.","Respectez toute règle interne plus stricte."],callout:{title:"Règle en vigueur en octobre 2026",text:"Le gouvernement fédéral a annoncé un durcissement, mais ses propres informations indiquent que les règles actuelles restent applicables jusqu'à la mise en œuvre effective des changements.",tone:"note"}},
      {heading:"Étape 2 : quand la confirmation médicale est requise",paragraphs:["Selon la règle légale actuelle, si l'incapacité dure plus de trois jours calendaires, une constatation médicale doit normalement exister au plus tard le jour ouvrable suivant. L'employeur peut l'exiger plus tôt, y compris dès le premier jour.","Deux salariés de deux entreprises différentes peuvent donc avoir des délais pratiques différents. Vérifiez contrat, convention collective et politique interne."],bullets:["Règle légale de base : plus de trois jours calendaires.","L'employeur peut exiger le certificat plus tôt.","Si l'arrêt se prolonge, une nouvelle constatation médicale est nécessaire."]},
      {heading:"Comment fonctionne l'eAU avec l'assurance publique",paragraphs:["Pour les salariés assurés dans le système public, la remise papier a largement été remplacée par l'elektronische Arbeitsunfähigkeitsbescheinigung (eAU). Le cabinet transmet les données à la caisse d'assurance, puis l'employeur récupère les informations pertinentes électroniquement.","L'eAU supprime généralement la remise du papier, pas l'obligation d'informer l'employeur. Conservez vos propres documents et dates.","Des exceptions peuvent subsister, notamment pour certaines assurances privées ou des soins hors du système conventionné."],resources:englishGuide.sickLeave.sections[2].resources},
      {heading:"Ce que signifie réellement la règle des six semaines",paragraphs:["Le §3 EntgFG prévoit jusqu'à six semaines de maintien du salaire par l'employeur lorsque les conditions légales sont remplies et que l'incapacité résulte d'une maladie sans faute du salarié.","Ne lisez pas 'six semaines' comme six nouvelles semaines automatiques à chaque absence. Une rechute liée à la même maladie ou une situation d'emploi particulière peut modifier le calcul."],callout:{title:"Pourquoi c'est important",text:"La première question pratique est de savoir qui vous paie pendant l'absence. Pour de nombreux salariés, l'employeur couvre la première période ; ensuite, l'indemnité maladie de l'assurance publique peut devenir pertinente.",tone:"success"}},
      {heading:"Arrêt par téléphone et téléconsultation en 2026",paragraphs:["La certification téléphonique pour certaines maladies légères existe encore au 8 octobre 2026. Le gouvernement fédéral a annoncé vouloir la supprimer, mais précise que les règles actuelles restent applicables jusqu'à leur remplacement.","Une annonce politique n'est pas encore une règle en vigueur. Vérifiez l'information fédérale ou demandez au cabinet si cette possibilité est importante pour vous."],resources:englishGuide.sickLeave.sections[4].resources},
      {heading:"Checklist simple pour un jour de maladie",paragraphs:["Une séquence utile est : prévenir l'employeur, vérifier le délai du certificat, contacter un cabinet si nécessaire, conserver les dates certifiées et informer à nouveau l'employeur si la date de retour change.","À l'étranger, avec une assurance privée, un Minijob dans un foyer privé ou un accident du travail, ne supposez pas que le circuit eAU standard s'applique sans modification."],bullets:["Prévenir l'employeur.","Vérifier le délai du certificat.","Obtenir la constatation médicale si nécessaire.","Conserver ses propres dates.","Signaler rapidement toute prolongation."]}
    ],
    faqs:[
      {question:"Dois-je encore prévenir mon employeur si le médecin envoie une eAU ?",answer:"Oui. L'eAU change la transmission des données médicales, pas votre obligation de signaler l'incapacité et sa durée prévue."},
      {question:"Ai-je toujours trois jours avant d'avoir besoin d'un certificat ?",answer:"Non. La règle actuelle vise les incapacités de plus de trois jours calendaires, mais l'employeur peut exiger une confirmation plus tôt, y compris dès le premier jour."},
      {question:"Le certificat dès le premier jour est-il déjà obligatoire pour tous en octobre 2026 ?",answer:"Non. Un durcissement a été annoncé, mais les règles actuelles restent applicables jusqu'à sa mise en œuvre."},
      {question:"L'arrêt maladie par téléphone existe-t-il encore ?",answer:"Oui dans les cas admissibles au 8 octobre 2026. Une suppression a été annoncée, donc il faudra revérifier ce point ultérieurement."}
    ],
    sources:englishGuide.sickLeave.sources
  },
  doctor:{
    ...englishGuide.doctor,
    slug:practicalGuideSlugs.doctor.fr,
    title:"Trouver un médecin en Allemagne : Hausarzt, 116117 et soins urgents",
    description:"Guide pratique pour trouver un Hausarzt ou un spécialiste, utiliser le 116117, comprendre le code de rendez-vous et distinguer cabinet, 116117 et 112.",
    eyebrow:"Guide pratique de santé",
    summary:"Le système de santé allemand devient plus simple si vous séparez trois besoins : le médecin habituel pour les soins courants, le 116117 pour rechercher des cabinets, obtenir certains rendez-vous et accéder aux soins urgents hors horaires, et le 112 pour les urgences vitales.",
    takeaways:["Le Hausarzt est généralement le meilleur premier contact pour les problèmes médicaux courants et le suivi.","Le service officiel 116117 propose une recherche de médecins et, pour les assurés publics, un service de rendez-vous.","Pour un rendez-vous de Hausarzt via 116117, aucune ordonnance de renvoi ni Vermittlungscode n'est requis.","116117 concerne les soins urgents mais non vitaux hors horaires ; 112 concerne les urgences vitales.","La recherche 116117 peut filtrer par spécialité et par critères supplémentaires comme les langues."],
    sections:[
      {heading:"Commencez par trouver un Hausarzt",paragraphs:["Le Hausarzt est le médecin généraliste ou médecin de famille et constitue souvent le meilleur premier point de contact pour maladies courantes, problèmes récurrents, vaccinations, contrôles de base et orientations vers des spécialistes.","L'Allemagne n'attribue pas automatiquement un médecin fixe à chaque nouvel arrivant. Vous cherchez vous-même un cabinet et demandez s'il accepte de nouveaux patients. La disponibilité varie fortement selon la ville."],bullets:["Chercher près du domicile, de l'université ou du travail.","Vérifier le type d'assurance accepté.","Demander si le cabinet accepte de nouveaux patients.","Enregistrer les horaires et le mode de prise de rendez-vous."]},
      {heading:"Utilisez la recherche officielle 116117",paragraphs:["Le service 116117 appartient au système de soins médicaux conventionnés. Sa recherche de médecins et psychothérapeutes permet de trouver des cabinets par zone, spécialité et autres critères.","C'est particulièrement utile lorsqu'une carte générale affiche de nombreux cabinets sans préciser clairement lesquels participent aux soins ambulatoires du système public. Les langues étrangères peuvent aussi apparaître dans les données des cabinets."],resources:englishGuide.doctor.sections[1].resources},
      {heading:"Quand le service de rendez-vous 116117 est utile",paragraphs:["Les personnes assurées dans le public peuvent utiliser 116117 pour réserver certains rendez-vous en ligne ou par téléphone. Les règles dépendent du type de médecin.","Selon la KBV, aucune ordonnance de renvoi ni Vermittlungscode n'est nécessaire pour un Hausarzt, un ophtalmologue, un gynécologue, un pédiatre ou une première consultation psychothérapeutique. Pour de nombreux autres spécialistes, un code peut être nécessaire via cette voie.","Cette exigence dans le service 116117 ne signifie pas qu'il est toujours impossible de contacter directement un spécialiste."],resources:englishGuide.doctor.sections[2].resources},
      {heading:"Distinguez 116117 et 112",paragraphs:["116117 est le service médical de garde pour les problèmes qui seraient normalement traités en cabinet mais ne peuvent raisonnablement attendre la prochaine ouverture.","112 est le numéro d'urgence pour les situations vitales. Détresse respiratoire sévère, perte de connaissance ou hémorragie majeure relèvent des secours d'urgence.","Si vous hésitez pour un problème non vital, le navigateur patient de 116117 peut vous orienter vers le niveau approprié. Il ne pose pas de diagnostic."],callout:{title:"Règle simple",text:"Problème normal pouvant attendre : cabinet. Problème urgent quand les cabinets sont fermés : 116117. Urgence vitale : 112.",tone:"warning"},resources:englishGuide.doctor.sections[3].resources},
      {heading:"Que préparer avant le rendez-vous",paragraphs:["Apportez votre carte d'assurance ou vos informations de couverture, la liste de vos médicaments et les documents médicaux pertinents. Si la langue vous inquiète, demandez à l'avance quelles langues sont réellement proposées.","Pour une maladie chronique, essayez de garder le même Hausarzt lorsque vous avez trouvé un cabinet adapté. Un médecin qui connaît votre historique peut mieux coordonner les orientations et le suivi."],bullets:["Carte/données d'assurance.","Liste des médicaments et allergies.","Courriers ou résultats utiles.","Petite liste de questions."]},
      {heading:"Un plan pratique pour un nouvel arrivant",paragraphs:["N'attendez pas d'être malade pour apprendre le système. Une fois votre couverture active, identifiez deux cabinets de Hausarzt proches, enregistrez 116117 et 112, et vérifiez comment votre assureur gère les soins courants.","Cette préparation vous donne une voie claire pour les soins normaux, les problèmes urgents hors horaires et les vraies urgences."]}
    ],
    faqs:[
      {question:"Ai-je besoin d'une ordonnance de renvoi pour voir un Hausarzt ?",answer:"Non. Le Hausarzt est le médecin de premier recours et le service de rendez-vous 116117 n'exige ni renvoi ni Vermittlungscode pour un rendez-vous de Hausarzt."},
      {question:"116117 peut-il m'aider à trouver un médecin anglophone ?",answer:"La recherche officielle contient des filtres supplémentaires et les cabinets peuvent indiquer des langues étrangères. La disponibilité dépend de la zone."},
      {question:"116117 est-il un numéro d'urgence ?",answer:"Il sert aux soins urgents non vitaux et à l'orientation/prise de rendez-vous. Pour une urgence vitale, appelez le 112."},
      {question:"Les assurés privés peuvent-ils utiliser 116117 ?",answer:"Le service médical de garde est disponible indépendamment du type d'assurance ; le service formel de rendez-vous est surtout destiné aux assurés publics."}
    ],
    sources:englishGuide.doctor.sources
  },
  payslip:{
    ...englishGuide.payslip,
    slug:practicalGuideSlugs.payslip.fr,
    title:"Fiche de paie allemande expliquée : Brutto, Netto, impôts et cotisations",
    description:"Comment lire une Lohnabrechnung ou Gehaltsabrechnung allemande, ce que l'employeur doit afficher, ce que signifient les principales retenues et pourquoi le net varie.",
    eyebrow:"Guide pratique du salaire",
    summary:"Une fiche de paie allemande devient plus simple si vous la séparez en quatre niveaux : rémunération brute, données fiscales, cotisations sociales et montant final versé. La présentation varie, mais le document doit identifier la période et la composition de la rémunération.",
    takeaways:["Le §108 GewO exige en principe un décompte de rémunération en format texte lors du paiement, avec une exception lorsque les informations pertinentes n'ont pas changé depuis le dernier décompte correct.","Le document doit identifier la période et la composition du salaire, y compris suppléments, indemnités et retenues pertinentes.","Brutto n'est pas le montant versé sur le compte ; Netto est obtenu après l'impôt sur salaire et les cotisations applicables.","La Lohnsteuer est calculée via le système de paie à partir de règles annualisées et des caractéristiques fiscales électroniques du salarié.","Prime, absence non payée, changement fiscal ou paiement exceptionnel peuvent modifier le net d'un mois à l'autre."],
    sections:[
      {heading:"Les quatre blocs d'une fiche de paie allemande",paragraphs:["La mise en page varie, mais on peut généralement distinguer quatre blocs : données du salarié et de paie, rémunération brute, retenues et montant final versé.","Ne commencez pas par chaque abréviation. Vérifiez d'abord la période, le brut et le montant versé, puis suivez les lignes qui expliquent l'écart."],bullets:["Période et données du salarié.","Salaire brut, primes et suppléments.","Impôts et cotisations sociales.","Net et montant effectivement versé."]},
      {heading:"Ce que l'employeur doit fournir",paragraphs:["Le §108 GewO impose un décompte de rémunération en format texte lors du paiement. Il doit au minimum indiquer la période de calcul et la composition de la rémunération.","La loi mentionne notamment le type et le montant des suppléments, indemnités et autres rémunérations ainsi que les retenues, avances et acomptes. Si les informations pertinentes n'ont pas changé depuis le dernier décompte correct, un nouveau document peut ne pas être nécessaire."],resources:englishGuide.payslip.sections[1].resources},
      {heading:"Brutto : ce qui apparaît avant les retenues",paragraphs:["Le salaire de base contractuel constitue généralement le point de départ. Selon l'emploi, le brut peut aussi inclure heures supplémentaires, travail posté, primes, commissions, paiements exceptionnels, avantages ou corrections.","Un brut plus élevé ne produit pas toujours une hausse proportionnelle du net, car l'impôt est annualisé et certaines cotisations ont des seuils ou plafonds."],callout:{title:"Contrôle utile",text:"Si le brut est faux, vérifiez d'abord les heures, la prime ou le salaire de base. Un calcul fiscal parfaitement correct peut produire un mauvais paiement si l'entrée de départ est erronée.",tone:"note"}},
      {heading:"Lohnsteuer, Kirchensteuer et Solidaritätszuschlag",paragraphs:["La Lohnsteuer est l'impôt sur salaire retenu par l'employeur. Le ministère fédéral des Finances explique que le salaire courant est converti en salaire annuel pour le calcul et que les caractéristiques électroniques comme la classe fiscale et certains abattements sont prises en compte.","La Kirchensteuer n'apparaît que si le salarié y est assujetti. Le Solidaritätszuschlag n'est pas une retenue forfaitaire payée par tous ; il dépend du calcul applicable.","Un changement de classe fiscale ou d'une autre caractéristique électronique peut n'apparaître que sur une paie ultérieure, une fois les données mises à jour."],resources:englishGuide.payslip.sections[3].resources},
      {heading:"Les abréviations des cotisations sociales",paragraphs:["Pour les salariés soumis à la sécurité sociale allemande, les lignes courantes sont assurance maladie (KV), retraite (RV), chômage (AV) et dépendance (PV). Le montant salarié dépend du type d'emploi et des assiettes/plafonds applicables.","Un Minijob, Midijob, Werkstudent ou emploi classique peuvent donc présenter des retenues très différentes malgré des salaires bruts proches."],bullets:["KV — Krankenversicherung (assurance maladie).","RV — Rentenversicherung (retraite).","AV — Arbeitslosenversicherung (chômage).","PV — Pflegeversicherung (dépendance)."]},
      {heading:"Pourquoi le montant versé peut différer du Netto",paragraphs:["De nombreuses fiches distinguent le net calculé du montant effectivement viré. Remboursements, avantages, avances, saisies ou autres éléments de règlement peuvent se trouver entre les deux.","Si le virement bancaire ne correspond pas au premier montant net, cherchez une ligne Auszahlungsbetrag ou équivalente avant de conclure à une erreur." ]},
      {heading:"Contrôle de la fiche en cinq minutes",paragraphs:["Vérifiez période, brut contractuel, éléments variables, caractéristiques fiscales, statut d'assurance et paiement final. Comparez les changements inhabituels avec le mois précédent plutôt que de décoder tous les codes séparément.","Si quelque chose reste incohérent, demandez au service paie ou aux RH quelle donnée a changé. Pour une question fiscale, le Finanzamt ou un professionnel peut être compétent ; pour l'assurance, demandez à la caisse concernée."],bullets:["Le brut est-il correct ?","Heures supplémentaires, primes et absences sont-elles reflétées ?","La classe fiscale semble-t-elle correcte ?","Les cotisations correspondent-elles au type d'emploi ?","Le montant final correspond-il au compte bancaire ?"]}
    ],
    faqs:[
      {question:"Mon employeur doit-il me remettre une fiche de paie chaque mois ?",answer:"La loi exige en principe un décompte en format texte lors du paiement, mais l'obligation peut disparaître si les informations pertinentes n'ont pas changé depuis le dernier décompte correct."},
      {question:"Pourquoi mon salaire net est-il différent ce mois-ci ?",answer:"Les causes fréquentes sont primes, heures supplémentaires, absence non payée, changement fiscal, correction de paie ou paiement exceptionnel."},
      {question:"Quelle différence entre Netto et Auszahlungsbetrag ?",answer:"Netto est le résultat après les principales retenues de paie. D'autres éléments de règlement peuvent encore modifier le montant final versé."},
      {question:"Peut-on calculer le net allemand avec un pourcentage fixe ?",answer:"Pas de manière fiable. L'impôt sur salaire utilise des règles annualisées et des caractéristiques individuelles ; les cotisations dépendent du type d'emploi et des plafonds."}
    ],
    sources:englishGuide.payslip.sources
  }
};

const localized = { es, de, fr } as const;

export function practicalGuideKeyFromSlug(locale: "en"|"es"|"de"|"fr", slug: string): PracticalGuideKey | null {
  for (const key of Object.keys(practicalGuideSlugs) as PracticalGuideKey[]) if (practicalGuideSlugs[key][locale] === slug) return key;
  return null;
}

export function getLocalizedPracticalGuide(locale: "en"|"es"|"de"|"fr", key: PracticalGuideKey): Guide {
  if (locale === "en") return { ...englishGuide[key], slug: practicalGuideSlugs[key].en };
  return localized[locale][key];
}

export function practicalGuidePath(locale: "en"|"es"|"de"|"fr", key: PracticalGuideKey) {
  return locale === "en" ? `/guides/${practicalGuideSlugs[key].en}` : `/${locale}/guides/${practicalGuideSlugs[key][locale]}`;
}

export function practicalGuideStaticParams(locale: "en"|"es"|"de"|"fr") {
  return (Object.keys(practicalGuideSlugs) as PracticalGuideKey[]).map((key)=>({slug:practicalGuideSlugs[key][locale]}));
}
