import type { Guide } from "@/lib/types";

const employment = { name: "Federal Employment Agency", url: "https://www.arbeitsagentur.de/en", note: "Official employment information and job search" };
const makeIt = { name: "Make it in Germany", url: "https://www.make-it-in-germany.com/en/working-in-germany", note: "Official information for international professionals" };
const minijob = { name: "Minijob-Zentrale", url: "https://www.minijob-zentrale.de/EN/Home/home_node.html", note: "Official information for marginal employment" };
const studentWork = { name: "German Student Services", url: "https://www.studierendenwerke.de/en/topics/jobben", note: "Student work overview" };
const tenant = { name: "Federal Ministry of Justice — laws", url: "https://www.gesetze-im-internet.de/englisch_bgb/", note: "Official English translation of the German Civil Code" };
const schufaSource = { name: "SCHUFA", url: "https://www.schufa.de/en/", note: "Information from the credit bureau" };

export const workAndHousingGuides: Guide[] = [
  {
    slug: "finding-housing-germany", title: "Finding housing in Germany: a safer, stronger search", description: "Build a credible rental application, search across the right channels, and recognise common housing scams in Germany.", category: "housing", eyebrow: "Housing", updated: "2026-09-23", readingMinutes: 10, featured: true,
    summary: "Treat a German housing search like a pipeline: define a realistic area and budget, prepare documents, respond clearly, verify every listing, and track applications without sending unnecessary personal data.",
    takeaways: ["Compare Warmmiete, not only the headline Kaltmiete.", "Prepare documents, but minimise sensitive data until the recipient is verified.", "Confirm that Anmeldung is possible.", "Never let urgency replace identity, contract, and payment checks."],
    sections: [
      { heading: "Define a realistic search", paragraphs: ["Set a maximum total housing cost, not only base rent. Include service charges, heating arrangements, electricity, internet, transport, and any furnishing premium. Then map areas by door-to-door journey at the times you will travel.", "Use a mix of large property portals, housing companies, cooperatives, reputable temporary-housing services, local boards, and personal networks. WG listings are often conversational, while full-apartment applications may be more document-led."], bullets: ["Maximum warm rent and total monthly cost", "Move-in range", "Minimum contract length you can accept", "Maximum commute", "Whether Anmeldung must be possible", "Accessibility or household requirements"] },
      { heading: "Create a careful application pack", paragraphs: ["A concise introduction can state who will live there, work or study situation, intended move date, and availability for a viewing. Supporting documents may include proof of income or status, identity, and credit information, but requests vary.", "Redact information that is not necessary for the current stage. Send more sensitive documents only after you have verified the recipient and understand why they are needed."], callout: { title: "Data minimisation matters", text: "A competitive market is not a reason to send an unredacted passport, bank data, and salary history to an unverified address.", tone: "warning" } },
      { heading: "Check the home and the agreement", paragraphs: ["View the property in person when possible, or use a trusted representative and a live viewing. Confirm the address, identity and role of the person offering it, rent components, deposit, included furniture, defects, and handover process.", "Read the full contract before transferring money. Search the wording you do not understand and ask for clarification in writing. A legitimate opportunity should survive basic due diligence." ] },
      { heading: "Recognise scam patterns", paragraphs: ["Common warning signs include a price far below comparable homes, a supposed owner abroad, refusal to show the property, pressure to transfer before verification, payment through unusual channels, copied photographs, or inconsistent identities.", "Do not send money to ‘reserve’ a property solely on the basis of messages and images. If something feels wrong, stop and verify independently." ] },
    ],
    faqs: [
      { question: "What documents should I prepare?", answer: "Prepare proof of identity and ability to pay, plus a concise applicant profile. The exact pack varies. Share sensitive documents in stages and only with verified recipients." },
      { question: "Can I find housing before I arrive?", answer: "Yes, but remote searches carry additional fraud risk. Reputable temporary accommodation can provide time for an in-person long-term search." },
      { question: "What is a WG?", answer: "A Wohngemeinschaft is a shared household. You normally rent a room and share common spaces; clarify the contract structure and whether registration is possible." },
    ], sources: [tenant, schufaSource], related: ["renting-in-germany", "schufa-germany", "anmeldung-germany", "cost-of-living-germany"],
  },
  {
    slug: "renting-in-germany", title: "Renting in Germany: contracts, deposits, and handover", description: "Understand the main parts of a German residential lease, from cold and warm rent to deposits, defects, notice, and handover records.", category: "housing", eyebrow: "Housing", updated: "2026-09-23", readingMinutes: 10,
    summary: "A rental agreement is a long-term legal commitment. Read every cost, term, and attachment; document the condition at handover; and seek qualified help before acting on a serious dispute.",
    takeaways: ["Kaltmiete and Warmmiete describe different cost layers.", "Utilities and heating arrangements must be checked rather than assumed.", "The handover record protects both sides.", "Notice, subletting, and renovation clauses deserve careful reading."],
    sections: [
      { heading: "Read the cost structure", paragraphs: ["Kaltmiete is the base rent. Warmmiete usually combines base rent with specified operating-cost advances, but it may not include every recurring cost. Electricity, internet, and sometimes heating arrangements can sit outside the amount advertised.", "Ask which costs are advances subject to later reconciliation, which are fixed, and which contracts you arrange yourself. Build your budget from the contract, not the listing headline." ] },
      { heading: "Understand the commitment", paragraphs: ["Check whether the lease is open-ended or fixed-term, how termination works, whether a minimum term exists, and what the contract says about subletting, pets, shared use, furnishing, and house rules.", "Do not assume a clause is enforceable merely because it appears in a template, but do not ignore it either. A tenants' association or qualified lawyer can assess a concrete agreement."], callout: { title: "Legal questions need the actual contract", text: "General guides cannot determine your rights in a dispute. Preserve the agreement and correspondence and obtain qualified advice.", tone: "note" } },
      { heading: "Deposit and payment", paragraphs: ["The contract should identify the deposit and payment instructions. Verify the recipient and bank details independently, especially when communication has been remote.", "German law contains rules on residential security deposits. For the current legal position and your facts, consult the statutory text or qualified advice rather than relying on a listing's summary." ] },
      { heading: "Make the handover evidence-based", paragraphs: ["Inspect the home in good light. Record meter readings, keys, furniture, walls, floors, appliances, moisture, and existing damage in a signed handover protocol. Take dated photographs for your records.", "Report newly discovered problems promptly in writing and retain proof. On departure, repeat the process and agree how keys are returned." ] },
    ],
    faqs: [
      { question: "Does Warmmiete include everything?", answer: "No. The included items depend on the agreement. Electricity, internet, and other costs may be separate." },
      { question: "Should I pay before signing?", answer: "Do not transfer money simply to secure a viewing or on the basis of an unverified listing. Review the agreement, verify the parties, and understand the payment basis." },
      { question: "Where can I get help with a contract?", answer: "Local tenants' associations and lawyers specialising in tenancy law can review concrete documents and disputes." },
    ], sources: [tenant], related: ["finding-housing-germany", "schufa-germany", "wohnungsgeberbestaetigung", "cost-of-living-germany"],
  },
  {
    slug: "schufa-germany", title: "SCHUFA in Germany: what newcomers need to know", description: "A neutral explanation of SCHUFA, data copies, landlord requests, and responsible handling of German credit information.", category: "money", eyebrow: "Money", updated: "2026-09-23", readingMinutes: 7,
    summary: "SCHUFA is a private credit bureau, not a government register. A landlord may ask for credit-related evidence, but you should understand which document is requested and avoid oversharing personal information.",
    takeaways: ["SCHUFA is a private company.", "A personal data copy and a product intended for third parties are not the same thing.", "New arrivals may have little German credit history.", "Challenge inaccurate data through the official process."],
    sections: [
      { heading: "What SCHUFA does", paragraphs: ["SCHUFA collects and processes credit-related information from participating organisations and produces information used in risk decisions. It does not decide whether you receive an apartment, account, or contract; the requesting organisation makes that decision.", "A thin file is not automatically a negative record. Newcomers may simply have limited German history." ] },
      { heading: "Choose the right document", paragraphs: ["Different SCHUFA documents serve different purposes. A detailed data-access copy can contain information you may not want to hand to every landlord. A landlord-oriented certificate is designed for sharing but may be a paid product.", "Read SCHUFA's current descriptions before ordering. Do not upload a full data copy publicly or send it indiscriminately."], callout: { title: "Protect the full record", text: "Share the minimum document needed with a verified recipient. Credit information can expose sensitive personal data.", tone: "warning" } },
      { heading: "If information is wrong", paragraphs: ["Obtain the relevant record, identify the disputed entry, collect supporting evidence, and use the bureau's official correction channel. The organisation that supplied the data may also need to investigate.", "Keep correspondence and dates. For unresolved issues or legal consequences, seek help from a consumer advice centre or qualified professional." ] },
    ],
    faqs: [
      { question: "Do I need SCHUFA to rent?", answer: "It is commonly requested, but application requirements vary. Ask what evidence the landlord accepts, especially if you are new to Germany." },
      { question: "Is no SCHUFA history bad?", answer: "It can mean that a landlord has less information, not that you have a negative entry. Other evidence of affordability may help." },
      { question: "Can I see my data?", answer: "Yes. Review the options on SCHUFA's official site, including the statutory data-access route and products designed for third-party sharing." },
    ], sources: [schufaSource], related: ["finding-housing-germany", "renting-in-germany", "german-bank-account", "cost-of-living-germany"],
  },
  {
    slug: "working-in-germany", title: "Working in Germany: contracts, pay, and your first weeks", description: "A practical introduction to work authorisation, German employment contracts, payroll documents, probation, leave, and workplace setup.", category: "work", eyebrow: "Work", updated: "2026-09-23", readingMinutes: 11, featured: true,
    summary: "Before starting a job, confirm that your status permits the work, identify the legal employer, read the full contract, and understand gross pay, working time, probation, notice, and the documents payroll needs.",
    takeaways: ["A job offer and permission to work are separate questions.", "Compare salary as gross compensation and understand deductions.", "Read probation and notice clauses before signing.", "Keep contracts, payslips, time records, and formal correspondence."],
    sections: [
      { heading: "Confirm the right to do the work", paragraphs: ["EU citizens and different groups of non-EU nationals follow different rules. For non-EU citizens, a residence title may allow a specific role, employer, or form of work—or may contain restrictions.", "Use the official immigration route for your circumstances. Do not rely on the recruiter's confidence as a substitute for the wording of your permission." ] },
      { heading: "Read the complete offer", paragraphs: ["Identify the employing legal entity, workplace or remote-work terms, start date, role, gross compensation, working hours, probation, holiday, notice, overtime handling, collective agreements, and any variable pay.", "Benefits can be valuable, but compare the guaranteed package first. Ask for unclear verbal promises to be reflected in the written agreement."], bullets: ["Gross annual or monthly pay", "Fixed and variable components", "Weekly hours and overtime", "Work location and travel", "Probation and notice", "Holiday entitlement", "Side-work and confidentiality clauses"] },
      { heading: "Set up payroll", paragraphs: ["An employer typically needs identity and payment details plus the identifiers and insurance information relevant to payroll. If your Tax ID or another document is pending, tell payroll early and ask how they will handle it.", "Read each payslip. Learn the difference between gross pay, statutory deductions, other deductions, and the net transfer. Raise discrepancies promptly." ] },
      { heading: "Protect the employment record", paragraphs: ["Keep the signed contract, amendments, payslips, leave records, sickness notifications, and important messages. Follow the employer's reporting process if you are ill or absent.", "Deadlines can be short in employment disputes. For a dismissal, unpaid wages, or a serious conflict, obtain qualified advice promptly rather than waiting for a general guide."], callout: { title: "Time matters in disputes", text: "Employment-law deadlines may be strict. Contact a union, advice service, or qualified lawyer quickly if a decision affects your job.", tone: "warning" } },
    ],
    faqs: [
      { question: "Is the salary figure gross or net?", answer: "German job offers normally state gross pay. Net pay depends on personal tax and social-insurance circumstances." },
      { question: "Can I work before receiving my Tax ID?", answer: "Discuss the situation with payroll. Your permission to work and your payroll administration are separate matters." },
      { question: "Should I sign a contract I do not fully understand?", answer: "No. Ask for clarification and, for significant uncertainty, have the contract reviewed before signing." },
    ], sources: [employment, makeIt], related: ["jobs-without-german", "german-tax-id", "german-health-insurance", "cost-of-living-germany"],
  },
  {
    slug: "jobs-without-german", title: "Finding a job in Germany without fluent German", description: "Target realistic English-speaking roles, show your value clearly, and build a job search that does not depend on misleading promises.", category: "work", eyebrow: "Work", updated: "2026-09-23", readingMinutes: 9,
    summary: "English-speaking work exists, but availability depends heavily on field, seniority, location, and whether the role serves German-speaking customers or regulated processes. A focused search beats applying everywhere.",
    takeaways: ["Target roles where your language profile is operationally credible.", "State your German level honestly.", "Use official and employer-direct sources alongside job boards.", "A basic German learning plan strengthens both work and daily life."],
    sections: [
      { heading: "Find the realistic segment", paragraphs: ["International technology, research, certain corporate functions, startups, and globally oriented employers may use English internally. Customer-facing, healthcare, public-sector, legal, education, and many local operations roles often need German for practical or regulated reasons.", "Search by function, company working language, and actual job description. ‘English-speaking’ in an advert does not always mean German is irrelevant." ] },
      { heading: "Make your application easy to evaluate", paragraphs: ["Lead with evidence relevant to the role: results, tools, domain knowledge, portfolio, and the right to work or route you are pursuing. Use a clean CV that a recruiter can scan quickly.", "List language levels using a recognised scale if you can defend the assessment. Do not describe beginner German as fluent or hide a role's explicit requirement."], bullets: ["Role-specific opening summary", "Achievement-focused experience", "Clear location and availability", "Honest language level", "Work-authorisation context stated carefully", "Portfolio or evidence where relevant"] },
      { heading: "Run a measured search", paragraphs: ["Build a target list of employers, follow their career pages, use the Federal Employment Agency and reputable platforms, and speak to people doing similar work. Track response rates by role type and adjust the positioning—not just the application volume.", "Be cautious with agencies promising guaranteed jobs, visa outcomes, or paid access to ordinary vacancies."], callout: { title: "No one can guarantee a visa or job", text: "Verify recruiters, employers, and contracts independently before paying fees or sharing sensitive documents.", tone: "warning" } },
    ],
    faqs: [
      { question: "Can I build a career in Germany using only English?", answer: "Some people do, especially in internationally oriented fields, but options vary. German expands the range of employers and makes everyday administration easier." },
      { question: "Should I translate my CV into German?", answer: "Use the language requested in the advert. A poor automated translation can be worse than a strong English application for an English-language role." },
      { question: "Where should I search?", answer: "Combine employer career pages, the Federal Employment Agency, specialist boards, professional networks, and credible recruiters." },
    ], sources: [employment, makeIt], related: ["working-in-germany", "moving-to-germany", "best-cities-germany", "cost-of-living-germany"],
  },
  {
    slug: "minijob-germany", title: "Minijobs in Germany: understand the employment type", description: "Learn how Germany's marginal employment category works, what to check in a contract, and why the current official thresholds matter.", category: "work", eyebrow: "Work", updated: "2026-09-23", readingMinutes: 7,
    summary: "A Minijob is a regulated employment category, not casual work outside employment law. Thresholds and contribution rules can change, so check the Minijob-Zentrale before relying on a figure.",
    takeaways: ["Use the current official earnings threshold.", "Minijob workers still have employment rights.", "Multiple jobs can change the classification.", "International residents must confirm that their status permits the work."],
    sections: [
      { heading: "Start with the current definition", paragraphs: ["The earnings threshold is linked to legal rules and can change. Instead of copying an old figure from a forum, use the Minijob-Zentrale's current explanation and examples.", "The classification can depend on regular expected earnings and on other employment. Tell the employer accurately about relevant additional jobs." ] },
      { heading: "Read it like any employment contract", paragraphs: ["Check the employer, duties, place of work, hourly rate, expected hours, scheduling, holiday, sickness reporting, probation, and notice. Keep your own time record and payslips.", "A Minijob label does not remove minimum employment protections. If the practical arrangement differs from the contract, ask for clarification in writing." ] },
      { heading: "Check your wider situation", paragraphs: ["Students, pensioners, people with a main job, and international residents can face different interactions with insurance, tax, or residence conditions. Use the official calculator and guidance, then ask the responsible institution about your facts.", "Do not assume a Minijob automatically provides comprehensive health insurance or permission to work."], callout: { title: "Category is not coverage", text: "Confirm health insurance and residence conditions separately; the job label does not answer either question.", tone: "warning" } },
    ],
    faqs: [
      { question: "What is the current Minijob limit?", answer: "The threshold can change. Check the current figure directly with the Minijob-Zentrale before making a decision." },
      { question: "Do Minijob workers get paid holiday?", answer: "Minijob workers are employees and employment protections apply. The amount depends on the working pattern and legal context." },
      { question: "Can an international student take a Minijob?", answer: "Possibly, but residence and student-work conditions can apply. Confirm the rules for your status." },
    ], sources: [minijob], related: ["working-in-germany", "werkstudent-germany", "german-health-insurance", "german-tax-id"],
  },
  {
    slug: "werkstudent-germany", title: "Werkstudent jobs in Germany: a student-first guide", description: "Understand the working-student model, study priority, contracts, insurance questions, and checks for international students.", category: "work", eyebrow: "Work", updated: "2026-09-23", readingMinutes: 8,
    summary: "A Werkstudent role is employment alongside study, usually connected to special social-insurance treatment when study remains the main activity. The exact result depends on hours, timing, status, and other work.",
    takeaways: ["Enrolment alone does not settle every eligibility question.", "Working patterns during and outside lecture periods matter.", "International students must also follow residence conditions.", "Ask the employer and health insurer how the arrangement is classified."],
    sections: [
      { heading: "What makes the model different", paragraphs: ["Werkstudent is commonly used for students whose studies remain their principal activity. It is not simply a job title, internship synonym, or guarantee of a particular deduction.", "Employers assess the working pattern and request enrolment evidence. Tell them about other work because combined hours can matter." ] },
      { heading: "Review the role as both student and employee", paragraphs: ["Check how the job connects to your studies or career, but also read the ordinary employment terms: tasks, pay, hours, schedule, location, holiday, probation, notice, and overtime.", "Plan exam periods and timetable changes before agreeing to a rigid schedule. Clarify what happens during semester breaks." ] },
      { heading: "Confirm insurance and residence effects", paragraphs: ["Ask your health insurer how the job affects your coverage and contributions. International students should verify permitted work and any limits through official immigration guidance.", "Keep enrolment certificates, the contract, time records, payslips, and correspondence about classification."], callout: { title: "Ask before the first payslip", text: "Have the employer and your health insurer explain how they will treat the role; fixing a misunderstanding later is harder.", tone: "note" } },
    ],
    faqs: [
      { question: "Is every student job a Werkstudent job?", answer: "No. The label and social-insurance treatment depend on the arrangement and your situation." },
      { question: "Can I have more than one job?", answer: "Possibly, but combined hours and earnings can affect classification and residence conditions. Disclose the relevant work to employers and ask the responsible institutions." },
      { question: "Does the role have to match my degree?", answer: "Not necessarily as a universal rule, though a relevant role may be more valuable for experience. Check the actual vacancy and employment classification." },
    ], sources: [studentWork, employment], related: ["minijob-germany", "working-in-germany", "german-health-insurance", "german-tax-id"],
  },
];
