"use client";

import Link from "next/link";
import { CategoryCard, CityCard, GuideCard, type CategoryCardData, type CityCardData, type GuideCardData } from "@/components/cards";
import { Icon } from "@/components/icon";
import { useLanguage } from "@/components/language-provider";
import { Newsletter } from "@/components/newsletter";
import type { IconName } from "@/lib/types";

type AudienceLinkData = { slug: string; name: string };
type Props = { popular: GuideCardData[]; latest: GuideCardData[]; categories: CategoryCardData[]; cities: CityCardData[]; audiences: AudienceLinkData[] };
type HomeCopy = {
  heroEyebrow: string; heroLead: string; heroAccent: string; heroText: string; start: string; exploreGuides: string; independent: string; sourceLed: string; updated: string;
  before: string; after: string; plan: string; move: string; register: string; setUp: string; home: string; practicalRoute: string; routeFrom: string; routeTo: string;
  planningEyebrow: string; planningTitle: string; planningText: string; planCta: string; systemsEyebrow: string; systemsTitle: string; systemsText: string;
  newHere: string; weeksTitle: string; weeksText: string; fullChecklist: string; popular: string; popularTitle: string; allGuides: string; cityEyebrow: string; cityTitle: string; cityText: string; allCities: string;
  audienceEyebrow: string; audienceTitle: string; toolsEyebrow: string; toolsTitle: string; toolsText: string; openTools: string; latest: string; recent: string;
  actionCards: readonly (readonly [string, string, string, string])[]; arrivalSteps: readonly (readonly [string, string, string])[]; tools: readonly (readonly [IconName, string, string])[];
};

const english: HomeCopy = {
  heroEyebrow: "Independent practical guidance", heroLead: "Living in Germany,", heroAccent: "made clear.", heroText: "Everything you need to move, work, and build your life in Germany—explained with context, official sources, and no sales pressure.", start: "Start here", exploreGuides: "Explore guides", independent: "Independent", sourceLed: "Source-led", updated: "Updated clearly",
  before: "Before", after: "After", plan: "Plan", move: "Move", register: "Register", setUp: "Set up", home: "Home", practicalRoute: "The practical route", routeFrom: "From “where do I begin?”", routeTo: "to “I know what comes next.”",
  planningEyebrow: "Start with your next task", planningTitle: "What do you need help with?", planningText: "Choose the problem in front of you. You will get a practical route, examples, useful tools, and the official sources to check.", planCta: "Build my personal Germany plan", systemsEyebrow: "Living in Germany", systemsTitle: "The systems behind everyday life", systemsText: "Each hub connects the decisions, documents, and next steps around it.",
  newHere: "New to Germany?", weeksTitle: "Your first weeks, in a sensible order.", weeksText: "Not every task is equally urgent. This route puts legal, health, housing, and identity dependencies before optional contracts.", fullChecklist: "Open the full checklist", popular: "Popular guides", popularTitle: "Start with what matters most", allGuides: "View all guides", cityEyebrow: "Explore by city", cityTitle: "Where you live changes the answer", cityText: "Compare housing, transport, work, and local administration through a city-specific lens.", allCities: "Explore all cities",
  audienceEyebrow: "Built around you", audienceTitle: "Different routes. One clear starting point.", toolsEyebrow: "Tools & calculators", toolsTitle: "Make the next decision concrete", toolsText: "Transparent assumptions, local progress storage and clear limits.", openTools: "Open all tools", latest: "Latest guides", recent: "Recently added",
  actionCards: [["🧳", "I am moving to Germany", "Put visas, housing, Anmeldung and your first weeks in a sensible order.", "/plan"], ["💶", "I want to understand living costs", "Build a monthly budget from your rent, household and lifestyle.", "/tools/cost-of-living"], ["💼", "I have a job or job offer", "Check contracts, salary, Tax ID, insurance and payroll basics.", "/guides/working-in-germany"], ["🏠", "I need housing", "Find real portals, understand warm rent and spot common scams.", "/guides/finding-housing-germany"], ["📄", "I do not understand a document", "See what German documents mean, who sends them and what to do next.", "/guides/german-documents-explained"], ["🏙", "I am choosing a city", "Compare housing pressure, transport, jobs, study and local services.", "/explore-germany"], ["🎓", "I am studying in Germany", "Start with enrolment, insurance, work rules and student transport.", "/students"]],
  arrivalSteps: [["01", "Find registrable accommodation", "Confirm the provider can issue the move-in confirmation."], ["02", "Register your address", "Follow your municipality's current Anmeldung process."], ["03", "Confirm health insurance", "Choose the route that matches your work, study, or family status."], ["04", "Secure your identifiers", "Store registration and Tax ID documents safely."], ["05", "Set up everyday systems", "Banking, mobile, transport, post, and essential accounts."]],
  tools: [["check", "Document checklist", "Generate and track the documents relevant to your route."], ["wallet", "Cost-of-living calculator", "Build a budget from your real rent and inputs."], ["city", "City comparison", "Compare practical trade-offs across 2–4 cities."]],
};

const spanish: HomeCopy = {
  heroEyebrow: "Orientación práctica e independiente", heroLead: "Vivir en Alemania,", heroAccent: "sin complicaciones.", heroText: "Todo lo que necesitas para mudarte, trabajar y construir tu vida en Alemania, explicado con contexto, fuentes oficiales y sin presión comercial.", start: "Empieza aquí", exploreGuides: "Explorar guías", independent: "Independiente", sourceLed: "Basado en fuentes", updated: "Actualizado con claridad",
  before: "Antes", after: "Después", plan: "Planificar", move: "Mudarte", register: "Registrarte", setUp: "Instalarte", home: "Tu hogar", practicalRoute: "La ruta práctica", routeFrom: "De «¿por dónde empiezo?»", routeTo: "a «sé cuál es el siguiente paso».",
  planningEyebrow: "Empieza por tu siguiente tarea", planningTitle: "¿Con qué necesitas ayuda?", planningText: "Elige el problema que tienes delante. Encontrarás una ruta práctica, ejemplos, herramientas útiles y las fuentes oficiales que debes comprobar.", planCta: "Crear mi plan personal para Alemania", systemsEyebrow: "Vivir en Alemania", systemsTitle: "Los sistemas de la vida cotidiana", systemsText: "Cada área conecta las decisiones, los documentos y los siguientes pasos.",
  newHere: "¿Acabas de llegar a Alemania?", weeksTitle: "Tus primeras semanas, en un orden sensato.", weeksText: "No todas las tareas tienen la misma urgencia. Esta ruta prioriza los requisitos legales, de salud, vivienda e identidad antes que los contratos opcionales.", fullChecklist: "Abrir la lista completa", popular: "Guías populares", popularTitle: "Empieza por lo más importante", allGuides: "Ver todas las guías", cityEyebrow: "Explora por ciudad", cityTitle: "La ciudad cambia la respuesta", cityText: "Compara vivienda, transporte, trabajo y administración local desde la perspectiva de cada ciudad.", allCities: "Explorar todas las ciudades",
  audienceEyebrow: "Pensado para ti", audienceTitle: "Rutas diferentes. Un punto de partida claro.", toolsEyebrow: "Herramientas y calculadoras", toolsTitle: "Convierte la próxima decisión en algo concreto", toolsText: "Supuestos transparentes, progreso guardado en tu dispositivo y límites claros.", openTools: "Abrir todas las herramientas", latest: "Últimas guías", recent: "Añadidas recientemente",
  actionCards: [["🧳", "Me mudo a Alemania", "Ordena visado, vivienda, Anmeldung y tus primeras semanas.", "/plan"], ["💶", "Quiero entender el coste de vida", "Calcula un presupuesto mensual con tu alquiler, hogar y estilo de vida.", "/tools/cost-of-living"], ["💼", "Tengo trabajo o una oferta", "Revisa contrato, sueldo, Steuer-ID, seguro y nómina.", "/guides/working-in-germany"], ["🏠", "Necesito vivienda", "Encuentra portales reales, entiende el Warmmiete y detecta estafas.", "/guides/finding-housing-germany"], ["📄", "No entiendo un documento", "Descubre qué significa, quién lo envía y qué debes hacer después.", "/guides/german-documents-explained"], ["🏙", "Estoy eligiendo ciudad", "Compara vivienda, transporte, trabajo, estudios y servicios locales.", "/explore-germany"], ["🎓", "Voy a estudiar en Alemania", "Empieza por matrícula, seguro, trabajo y transporte de estudiante.", "/students"]],
  arrivalSteps: [["01", "Encuentra una vivienda registrable", "Confirma que pueden entregarte la confirmación del arrendador."], ["02", "Registra tu domicilio", "Sigue el proceso de Anmeldung vigente en tu municipio."], ["03", "Confirma tu seguro médico", "Elige la vía adecuada para tu trabajo, estudios o situación familiar."], ["04", "Protege tus identificadores", "Guarda de forma segura el registro y la identificación fiscal."], ["05", "Configura los servicios cotidianos", "Banco, móvil, transporte, correo y cuentas esenciales."]],
  tools: [["check", "Lista de documentos", "Genera y controla los documentos relevantes para tu ruta."], ["wallet", "Calculadora del coste de vida", "Crea un presupuesto con tu alquiler y datos reales."], ["city", "Comparador de ciudades", "Compara aspectos prácticos de entre 2 y 4 ciudades."]],
};

const spanishCategoryNames: Record<string, [string, string]> = { "moving-to-germany": ["Mudarse a Alemania", "Planifica la mudanza, llega preparado y afronta tus primeras semanas con confianza."], work: ["Trabajar en Alemania", "Entiende la búsqueda de empleo, los contratos, el salario y los derechos laborales."], housing: ["Vivienda", "Encuentra casa, entiende el alquiler alemán y evita errores habituales."], bureaucracy: ["Trámites", "Ayuda clara con Anmeldung, identificadores, permisos y cartas oficiales."], money: ["Dinero e impuestos", "Banca, impuestos y pagos cotidianos explicados sin presión comercial."], healthcare: ["Salud y seguros", "Navega la cobertura médica, los médicos, las farmacias y los seguros."], transport: ["Transporte", "Entiende el transporte local, los trenes de larga distancia y los billetes."], "daily-life": ["Vida diaria", "Ayuda práctica con compras, conectividad, reciclaje, idioma y costumbres."] };
const spanishAudiences: Record<string, string> = { students: "Estudiantes", workers: "Trabajadores", families: "Familias", freelancers: "Autónomos", "eu-citizens": "Ciudadanos de la UE", "non-eu-citizens": "Ciudadanos no comunitarios" };
const spanishGuides: Record<string, string> = { "moving-to-germany": "Mudarse a Alemania: guía práctica de planificación", "first-30-days-germany": "Tus primeros 30 días en Alemania", "anmeldung-germany": "Anmeldung en Alemania: el registro de domicilio", "german-tax-id": "Identificación fiscal alemana: qué es y cómo encontrarla", "finding-housing-germany": "Buscar vivienda en Alemania de forma segura", "working-in-germany": "Trabajar en Alemania: contrato, salario y primeras semanas", "best-cities-germany": "Las mejores ciudades de Alemania según tus necesidades", "german-supermarkets": "Supermercados alemanes: compras, Pfand y pagos", "german-sim-cards": "Tarjetas SIM alemanas sin sorpresas contractuales" };

export function HomeContent({ popular, latest, categories, cities, audiences }: Props) {
  const { locale } = useLanguage();
  const c = locale === "es" ? spanish : english;
  const localCategory = (category: CategoryCardData): CategoryCardData => locale === "es" && spanishCategoryNames[category.slug] ? { ...category, name: spanishCategoryNames[category.slug][0], description: spanishCategoryNames[category.slug][1] } : category;
  const localGuide = (guide: GuideCardData): GuideCardData => locale === "es" && spanishGuides[guide.slug] ? { ...guide, title: spanishGuides[guide.slug] } : guide;

  return <>
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow hero-eyebrow"><span/> {c.heroEyebrow}</span><h1>{c.heroLead}<br/><em>{c.heroAccent}</em></h1><p>{c.heroText}</p><div className="hero-actions"><Link className="button button-primary button-large" href="/guides/first-30-days-germany">{c.start} <Icon name="arrow"/></Link><Link className="button button-secondary button-large" href="/guides">{c.exploreGuides}</Link></div><div className="trust-line"><span><Icon name="shield"/> {c.independent}</span><span><Icon name="check"/> {c.sourceLed}</span><span><Icon name="clock"/> {c.updated}</span></div></div><div className="hero-map" aria-label={c.practicalRoute}><div className="map-label top">{c.before}</div><div className="map-label bottom">{c.after}</div><div className="map-route"><svg className="route-line" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M 9 62 C 18 36, 31 24, 46 19 S 70 18, 80 34 S 92 53, 92 70"/></svg><span className="route-point p1"><b>1</b><small>{c.plan}</small></span><span className="route-point p2"><b>2</b><small>{c.move}</small></span><span className="route-point p3"><b>3</b><small>{c.register}</small></span><span className="route-point p4"><b>4</b><small>{c.setUp}</small></span><span className="route-point p5 active"><b><Icon name="home"/></b><small>{c.home}</small></span></div><div className="hero-note"><span>{c.practicalRoute}</span><strong>{c.routeFrom}<br/>{c.routeTo}</strong></div></div></div></section>
    <section className="section shell"><div className="section-heading"><div><span className="eyebrow">{c.planningEyebrow}</span><h2>{c.planningTitle}</h2></div><p>{c.planningText}</p></div><div className="action-card-grid">{c.actionCards.map(([symbol, title, text, href]) => <Link href={href} className="action-card" key={title}><span>{symbol}</span><strong>{title}</strong><small>{text}</small><Icon name="arrow"/></Link>)}</div><div className="center-action"><Link className="button button-primary button-large" href="/plan">{c.planCta} <Icon name="arrow"/></Link></div></section>
    <section className="section shell section-compact"><div className="section-heading"><div><span className="eyebrow">{c.systemsEyebrow}</span><h2>{c.systemsTitle}</h2></div><p>{c.systemsText}</p></div><div className="category-grid">{categories.map((category) => <CategoryCard key={category.slug} category={localCategory(category)}/>)}</div></section>
    <section className="arrival-section"><div className="shell arrival-grid"><div className="arrival-intro"><span className="eyebrow eyebrow-light">{c.newHere}</span><h2>{c.weeksTitle}</h2><p>{c.weeksText}</p><Link className="button button-light" href="/guides/first-30-days-germany">{c.fullChecklist} <Icon name="arrow"/></Link></div><ol className="arrival-list">{c.arrivalSteps.map(([number, title, text]) => <li key={number}><span>{number}</span><div><strong>{title}</strong><p>{text}</p></div></li>)}</ol></div></section>
    <section className="section shell"><div className="section-heading"><div><span className="eyebrow">{c.popular}</span><h2>{c.popularTitle}</h2></div><Link className="text-link" href="/guides">{c.allGuides} <Icon name="arrow" size={16}/></Link></div><div className="guide-grid">{popular.map((guide) => <GuideCard key={guide.slug} guide={localGuide(guide)}/>)}</div></section>
    <section className="section section-soft"><div className="shell"><div className="section-heading"><div><span className="eyebrow">{c.cityEyebrow}</span><h2>{c.cityTitle}</h2></div><p>{c.cityText}</p></div><div className="city-grid">{cities.map((city) => <CityCard key={city.slug} city={city}/>)}</div><div className="center-action"><Link className="button button-secondary" href="/cities">{c.allCities} <Icon name="arrow"/></Link></div></div></section>
    <section className="section shell"><div className="split-heading"><div><span className="eyebrow">{c.audienceEyebrow}</span><h2>{c.audienceTitle}</h2></div><div className="audience-links">{audiences.map((audience) => <Link key={audience.slug} href={`/${audience.slug}`}><span>{locale === "es" ? spanishAudiences[audience.slug] || audience.name : audience.name}</span><Icon name="arrow"/></Link>)}</div></div></section>
    <section className="section shell"><div className="section-heading"><div><span className="eyebrow">{c.toolsEyebrow}</span><h2>{c.toolsTitle}</h2></div><p>{c.toolsText}</p></div><div className="tool-preview">{c.tools.map(([icon, title, text]) => <div key={title}><Icon name={icon}/><strong>{title}</strong><span>{text}</span></div>)}<Link href="/tools">{c.openTools} <Icon name="arrow"/></Link></div></section>
    <section className="section shell latest-section"><div className="section-heading"><div><span className="eyebrow">{c.latest}</span><h2>{c.recent}</h2></div></div><div className="latest-list">{latest.map((guide, index) => <div key={guide.slug}><span>{String(index + 1).padStart(2, "0")}</span><GuideCard guide={localGuide(guide)} compact/></div>)}</div></section>
    <div className="shell newsletter-wrap"><Newsletter/></div>
  </>;
}
