export const exactGuideSlugs = {
  minimumWage: { en: "minimum-wage-germany-2026", es: "salario-minimo-alemania-2026", de: "mindestlohn-deutschland-2026", fr: "salaire-minimum-allemagne-2026", it: "salario-minimo-germania-2026", pt: "salario-minimo-alemanha-2026", pl: "placa-minimalna-niemcy-2026", uk: "minimalna-zarplata-nimechchyna-2026" },
  minijob: { en: "minijob-germany-2026", es: "minijob-alemania-2026", de: "minijob-deutschland-2026", fr: "minijob-allemagne-2026", it: "minijob-germania-2026", pt: "minijob-alemanha-2026", pl: "minijob-niemcy-2026", uk: "minijob-nimechchyna-2026" },
  midijob: { en: "midijob-germany-2026", es: "midijob-alemania-2026", de: "midijob-deutschland-2026", fr: "midijob-allemagne-2026", it: "midijob-germania-2026", pt: "midijob-alemanha-2026", pl: "midijob-niemcy-2026", uk: "midijob-nimechchyna-2026" },
  deutschlandticket: { en: "deutschlandticket-price-rules-2026", es: "deutschlandticket-precio-reglas-2026", de: "deutschlandticket-preis-regeln-2026", fr: "deutschlandticket-prix-regles-2026", it: "deutschlandticket-prezzo-regole-2026", pt: "deutschlandticket-preco-regras-2026", pl: "deutschlandticket-cena-zasady-2026", uk: "deutschlandticket-tsina-pravyla-2026" },
  rundfunk: { en: "rundfunkbeitrag-germany-2026", es: "rundfunkbeitrag-alemania-2026", de: "rundfunkbeitrag-deutschland-2026", fr: "rundfunkbeitrag-allemagne-2026", it: "rundfunkbeitrag-germania-2026", pt: "rundfunkbeitrag-alemanha-2026", pl: "rundfunkbeitrag-niemcy-2026", uk: "rundfunkbeitrag-nimechchyna-2026" },
  anmeldung: { en: "anmeldung-deadline-documents", es: "anmeldung-plazo-documentos", de: "anmeldung-frist-unterlagen", fr: "anmeldung-delai-documents", it: "anmeldung-scadenza-documenti", pt: "anmeldung-prazo-documentos", pl: "anmeldung-termin-dokumenty", uk: "anmeldung-strok-dokumenty" },
  health: { en: "health-insurance-cost-germany-2026", es: "seguro-medico-coste-alemania-2026", de: "krankenversicherung-kosten-deutschland-2026", fr: "assurance-maladie-cout-allemagne-2026", it: "assicurazione-sanitaria-costo-germania-2026", pt: "seguro-saude-custo-alemanha-2026", pl: "ubezpieczenie-zdrowotne-koszt-niemcy-2026", uk: "medychne-strakhuvannia-vartist-nimechchyna-2026" },
  allowance: { en: "tax-free-allowance-germany-2026", es: "minimo-exento-impuestos-alemania-2026", de: "grundfreibetrag-deutschland-2026", fr: "abattement-fiscal-allemagne-2026", it: "franchigia-fiscale-germania-2026", pt: "isencao-fiscal-alemanha-2026", pl: "kwota-wolna-niemcy-2026", uk: "neopodatkovuvanyi-minimum-nimechchyna-2026" },
  kindergeld: { en: "kindergeld-germany-2026", es: "kindergeld-alemania-2026", de: "kindergeld-deutschland-2026", fr: "kindergeld-allemagne-2026", it: "kindergeld-germania-2026", pt: "kindergeld-alemanha-2026", pl: "kindergeld-niemcy-2026", uk: "kindergeld-nimechchyna-2026" },
  deposit: { en: "rental-deposit-germany-three-month-rule", es: "fianza-alquiler-alemania-regla-tres-meses", de: "mietkaution-drei-monatsmieten", fr: "depot-garantie-location-allemagne", it: "deposito-affitto-germania", pt: "caucao-aluguel-alemanha", pl: "kaucja-mieszkanie-niemcy", uk: "zastava-orenda-nimechchyna" },
  leave: { en: "paid-holiday-days-germany", es: "dias-vacaciones-pagadas-alemania", de: "gesetzlicher-urlaubsanspruch-deutschland", fr: "conges-payes-allemagne", it: "ferie-pagate-germania", pt: "ferias-remuneradas-alemanha", pl: "platny-urlop-niemcy", uk: "oplachuvana-vidpustka-nimechchyna" },
  hours: { en: "working-hours-notice-period-germany", es: "jornada-laboral-preaviso-alemania", de: "arbeitszeit-kuendigungsfrist-deutschland", fr: "temps-travail-preavis-allemagne", it: "orario-lavoro-preavviso-germania", pt: "horario-trabalho-aviso-alemanha", pl: "czas-pracy-okres-wypowiedzenia-niemcy", uk: "robochyi-chas-strok-poperedzhennia-nimechchyna" },
} as const;

export type ExactGuideKey = keyof typeof exactGuideSlugs;
