import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { GermanyCityExplorer } from "@/components/germany-explorer";
import { cityProfiles, germanStates } from "@/lib/platform-data";
import { absoluteUrl } from "@/lib/site";

export const metadata: Metadata = { title: "Explore Germany", description: "Explore Germany's 16 federal states and practical city profiles for moving, work, study and daily life.", alternates: { canonical: absoluteUrl("/explore-germany") } };
export default function ExploreGermanyPage() { return <><section className="page-hero"><div className="shell"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Explore Germany" }]}/><div className="page-hero-grid"><div className="page-hero-copy"><span className="eyebrow">16 Bundesländer</span><h1>Find a German city that fits your life</h1><p>Filter by housing pressure and employment sector, then open the local guide for transport, universities, work and official services.</p></div><div className="page-stat"><span>City guides</span><strong>{cityProfiles.length}</strong><small>Useful comparisons, without pretending there is one “best” city</small></div></div></div></section><section className="section shell"><div className="section-heading"><div><span className="eyebrow">Interactive city finder</span><h2>Compare the trade-offs that matter to you</h2></div><p>Start broad, then verify the exact rent, commute, job or university offer before deciding.</p></div><GermanyCityExplorer/><div className="germany-explorer state-section"><div className="state-map" aria-label="Accessible overview of Germany's federal states">{germanStates.map(([state, capital], index) => <article key={state} style={{ "--state-index": index } as React.CSSProperties}><span>{String(index + 1).padStart(2, "0")}</span><strong>{state}</strong><small>Capital: {capital}</small></article>)}</div><aside><span className="eyebrow">Why state matters</span><h2>One country, many local systems</h2><p>Federal law sits beside state and municipal delivery. Appointments, universities, schools, transport networks and local services can feel very different.</p><Link className="button button-primary" href="/tools/compare-cities">Compare up to four cities</Link></aside></div></section></> }
